import React from 'react';
import { Helmet } from 'react-helmet';
import { Link } from 'react-router-dom';
import { ArrowLeft, ChevronRight, Shield } from 'lucide-react';

const BukhariPage: React.FC = () => {
  return (
    <div className="pt-24 pb-16">
      <Helmet>
        <title>Bukhari | DRDO TOT Products | Global Technocrats</title>
        <meta name="description" content="Bukhari is a space heating device designed and developed by DIPAS (DRDO) with multiple safety features and high efficiency." />
      </Helmet>

      <div className="container">
        {/* Breadcrumb */}
        <div className="flex items-center text-sm mb-6">
          <Link to="/" className="text-gray-500 hover:text-primary-500">Home</Link>
          <ChevronRight className="w-4 h-4 mx-2 text-gray-400" />
          <Link to="/products" className="text-gray-500 hover:text-primary-500">Products</Link>
          <ChevronRight className="w-4 h-4 mx-2 text-gray-400" />
          <Link to="/products/drdo" className="text-gray-500 hover:text-primary-500">DRDO TOT Products</Link>
          <ChevronRight className="w-4 h-4 mx-2 text-gray-400" />
          <span className="text-gray-800">Bukhari</span>
        </div>

        {/* Product Header */}
        <div className="flex flex-col md:flex-row gap-8 mb-12">
          <div className="md:w-1/2">
            <div className="w-full h-[460px] rounded-lg shadow-sm overflow-hidden">
              <img 
                src="/images/Bukhari-768x384.png" 
                alt="Bukhari Space Heating Device" 
                className="w-full h-full object-contain bg-gray-100"
              />
            </div>
          </div>
          <div className="md:w-1/2">
            <h1 className="text-3xl md:text-4xl font-bold mb-4">Bukhari</h1>
            <div className="flex items-center mb-6">
              <Shield className="w-5 h-5 text-primary-500 mr-2" />
              <span className="text-sm font-medium bg-primary-50 text-primary-700 py-1 px-3 rounded-full">DRDO TOT Product</span>
            </div>
            <p className="text-gray-700 mb-6">
              Bukhari is a space heating device designed and developed by DIPAS (DRDO) with multiple safety features, high efficiency, and environmental benefits for extreme cold environments.
            </p>
            <div className="bg-gray-50 p-6 rounded-lg">
              <h3 className="text-lg font-semibold mb-4">Key Features</h3>
              <ul className="space-y-2">
                <li className="flex items-start">
                  <div className="flex-shrink-0 w-5 h-5 bg-primary-500 rounded-full flex items-center justify-center mt-0.5">
                    <span className="text-white text-xs">✓</span>
                  </div>
                  <span className="ml-2">Multiple level safety features</span>
                </li>
                <li className="flex items-start">
                  <div className="flex-shrink-0 w-5 h-5 bg-primary-500 rounded-full flex items-center justify-center mt-0.5">
                    <span className="text-white text-xs">✓</span>
                  </div>
                  <span className="ml-2">Two-chambered design with solar-powered DC fan</span>
                </li>
                <li className="flex items-start">
                  <div className="flex-shrink-0 w-5 h-5 bg-primary-500 rounded-full flex items-center justify-center mt-0.5">
                    <span className="text-white text-xs">✓</span>
                  </div>
                  <span className="ml-2">Three burner stove for cooking and heating</span>
                </li>
                <li className="flex items-start">
                  <div className="flex-shrink-0 w-5 h-5 bg-primary-500 rounded-full flex items-center justify-center mt-0.5">
                    <span className="text-white text-xs">✓</span>
                  </div>
                  <span className="ml-2">Environmentally friendly operation</span>
                </li>
              </ul>
            </div>
          </div>
        </div>

        {/* Product Details */}
        <div className="bg-white p-8 rounded-lg shadow-sm border border-gray-100 mb-12">
          <h2 className="text-2xl font-bold mb-6">Product Description</h2>
          
          <h3 className="text-xl font-semibold mb-4">Safety Features</h3>
          <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
            <li><strong>Multiple Level Safety:</strong> Designed to protect against blasts generated by back-drafts.</li>
            <li><strong>Back-Draft Resistant Exhaust Vent:</strong> Ensures the device remains safe from any back-drafts.</li>
            <li><strong>Three Impact Braking Plates:</strong> Strategically placed between two chambers to enhance safety.</li>
            <li><strong>No Auto Ignition:</strong> In case the burner is extinguished, the Bukhari won't auto-ignite, ensuring user safety.</li>
            <li><strong>No Build-Up of Harmful Gases:</strong> The design ensures that no harmful gases or fumes accumulate in the room.</li>
          </ul>

          <h3 className="text-xl font-semibold mb-4">Efficiency</h3>
          <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
            <li><strong>Fuel Consumption:</strong> Highly fuel-efficient, consuming only 500-700 ml of kerosene per hour.</li>
            <li><strong>Maximal Heat Extraction:</strong> Designed to ensure there's no thermal wastage in the exhaust gases.</li>
            <li><strong>Heating Method:</strong> Efficiently warms the room using both convective and radiative heating methods.</li>
          </ul>

          <h3 className="text-xl font-semibold mb-4">Environmental Impact</h3>
          <p className="text-gray-700 mb-6">
            The Bukhari is environmentally friendly, preventing about one ton of CO2 and 0.3 tons of black carbon from being released into the environment annually.
          </p>

          <h3 className="text-xl font-semibold mb-4">Salient Features</h3>
          <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
            <li><strong>Two-Chambered Design:</strong> Unique design with one chamber for the hot air blower and another for flue gases.</li>
            <li><strong>Solar-Powered DC Fan:</strong> Uses a DC fan to circulate hot air, powered by solar energy stored in a battery.</li>
            <li><strong>Improved Maintenance-Free Exhaust Vent:</strong> Operates based on Bernoulli's principle, preventing fire hazards.</li>
            <li><strong>Three Burner Stove:</strong> Includes a three-burner stove for cooking, warming food, and heating water.</li>
            <li><strong>Controllable Blue Flame:</strong> Ensures there's no soot formation, keeping the environment clean.</li>
            <li><strong>Optimized Heat Extraction:</strong> Designed to extract maximum heat with minimal wastage.</li>
          </ul>
        </div>

        {/* Back Button */}
        <div className="flex justify-between items-center">
          <Link to="/products/drdo" className="inline-flex items-center text-primary-600 font-medium hover:text-primary-700">
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to DRDO TOT Products
          </Link>
          <Link to="/contact" className="btn btn-primary py-2.5 px-6">
            Request Information
          </Link>
        </div>
      </div>
    </div>
  );
};

export default BukhariPage;