(function(g){var window=this;'use strict';var $h=function(N){N.publish("cardstatechange",N.iG()&&N.yF()?1:0)},Ue=function(N,z){var v=g.z1(z),R=v?z:arguments;
for(v=v?0:1;v<R.length;v++){if(N==null)return;N=N[R[v]]}return N},IQl=function(N){var z=g.OV(N);
N=g.rv(N);return new g.ks(z.x,z.y,N.width,N.height)},XVl=function(N,z,v){var R=R===void 0?{}:R;
var C;return C=g.dY(N,z,function(){g.T6(C);v.apply(N,arguments)},R)},gz=function(N){N=g.Cm(N);
delete Bx[N];g.wE(Bx)&&A$&&A$.stop()},ud$=function(){A$||(A$=new g.cn(function(){r97()},20));
var N=A$;N.isActive()||N.start()},r97=function(){var N=g.jV();
g.Dl(Bx,function(z){c99(z,N)});
g.wE(Bx)||ud$()},pQ=function(N,z,v,R){g.L6.call(this);
if(!Array.isArray(N)||!Array.isArray(z))throw Error("Start and end parameters must be arrays");if(N.length!=z.length)throw Error("Start and end points must be the same length");this.W=N;this.L=z;this.duration=v;this.B=R;this.coords=[];this.progress=this.G=0;this.N=null},c99=function(N,z){z<N.startTime&&(N.endTime=z+N.endTime-N.startTime,N.startTime=z);
N.progress=(z-N.startTime)/(N.endTime-N.startTime);N.progress>1&&(N.progress=1);N.G=1E3/(z-N.N);N.N=z;qLZ(N,N.progress);N.progress==1?(N.V=0,gz(N),N.onFinish(),N.K9()):N.isPlaying()&&N.KR()},qLZ=function(N,z){typeof N.B==="function"&&(z=N.B(z));
N.coords=Array(N.W.length);for(var v=0;v<N.W.length;v++)N.coords[v]=(N.L[v]-N.W[v])*z+N.W[v]},MY9=function(N,z){g.q_.call(this,N);
this.coords=z.coords;this.x=z.coords[0];this.y=z.coords[1];this.z=z.coords[2];this.duration=z.duration;this.progress=z.progress;this.fps=z.G;this.state=z.V},kh=function(N,z,v,R,C){pQ.call(this,z,v,R,C);
this.element=N},wV$=function(N,z,v,R,C){if(z.length!=2||v.length!=2)throw Error("Start and end points must be 2D");
kh.call(this,N,z,v,R,C)},NGZ=function(N){return Math.pow(N,3)},zyl=function(N){return 3*N*N-2*N*N*N},vb8=function(N){g.H.call(this);
this.W=N||window;this.V=[]},Px=function(N){return N.baseUrl||null},Ve=function(N,z){return g.kK(g.OL(N,z),function(v){return!!v})},Ry8=function(N,z,v){function R(Zu){var Nx=Zu.hovercardButton;
if(!Nx)return null;Nx=Nx.subscribeButtonRenderer;if(!Nx)return null;var av=Z(Nx.unsubscribedButtonText),M=Z(Nx.subscribedButtonText);if(Nx.subscribed){var s2=Z(Nx.subscriberCountWithUnsubscribeText);var $m=Z(Nx.subscriberCountText)}else s2=Z(Nx.subscriberCountText),$m=Z(Nx.subscriberCountWithSubscribeText);var O2=null;if(Zu.signinEndpoint){O2=Ue(Zu,"signinEndpoint","webNavigationEndpointData","url");if(!O2){var m7,QU;O2=(QU=g.t((m7=Nx.signInEndpoint)==null?void 0:m7.commandMetadata,g.dF))==null?void 0:
QU.url}if(!O2)return null}return av&&(M||O2)?{subscribed:Nx.subscribed,subscribeText:av,subscribeCount:s2,unsubscribeText:M,unsubscribeCount:$m,enabled:Nx.enabled,signinUrl:O2,classic:Zu.useClassicSubscribeButton}:null}
function C(Zu){if(Zu){var Nx=[],av=Zu.videoId;av&&Nx.push("v="+av);(av=Zu.playlistId)&&Nx.push("list="+av);(Zu=Zu.startTimeSeconds)&&Nx.push("t="+Zu);return"/watch?"+Nx.join("&")}}
function Z(Zu){if(!Zu)return null;var Nx=Zu.simpleText;return Nx?Nx:Zu.runs?g.OL(Zu.runs,function(av){return av.text}).join(""):null}
z=z.endscreenElementRenderer;if(!z)return null;var Y=z.style,Q=z.endpoint||{},L=null,K=null,l=!1,W=null,G=null,x=null,e=null,d=!1,T=null,m=null,n=null,P=null,V=null,D=null;if(Y==="VIDEO")g.t(Q,g.SJ)?L=g.t(Q,g.SJ).url:(D=g.t(Q,g.wi),L=C(D)),K=!1,W=N,z.thumbnailOverlays?(l=z.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,G=Z(l.text),l=l.style==="LIVE"):G=Z(z.videoDuration);else if(Y==="PLAYLIST")g.t(Q,g.SJ)?L=g.t(Q,g.SJ).url:(D=g.t(Q,g.wi),L=C(D)),K=!1,W=N,x=Z(z.playlistLength);else if(Y===
"CHANNEL"){if(d=Ue(Q,"browseEndpoint","browseId"))e=d,L="/channel/"+e;K=!1;W="new";(d=!!z.isSubscribe)?T=R(z):m=Z(z.subscribersText)}else Y==="WEBSITE"?((n=Ue(Q,"urlEndpoint","url"))&&(L=n),K=!0,W="new",n=z.icon.thumbnails[0].url):Y==="CREATOR_MERCHANDISE"&&(z.productPrice&&(P=Z(z.productPrice)),z.additionalFeesText&&(V=Z(z.additionalFeesText)),(K=Ue(Q,"urlEndpoint","url"))&&(L=K),K=!0,W="new");N=Ue(z,"title","accessibility","accessibilityData","label");var c=z.endpoint?z.endpoint.clickTrackingParams:
null,r="";if(z.metadata){var Rv=Z(z.metadata);Rv&&(r=Rv)}return{id:"element-"+v,type:Y,title:Z(z.title),metadata:r,callToAction:Z(z.callToAction),xD:z.image,iconUrl:n,left:Number(z.left),width:Number(z.width),top:Number(z.top),aspectRatio:Number(z.aspectRatio),startMs:Math.floor(Number(z.startMs)),endMs:Math.floor(Number(z.endMs)),videoDuration:G,dB:l,playlistLength:x,channelId:e,subscribeButton:T,subscribersText:m,isSubscribe:d,targetUrl:L||null,p6:K,sessionData:c?{itct:c}:null,tNp:W,l1:N?N:null,
isPlaceholder:z.isPlaceholder,impressionUrls:Ve(z.impressionUrls||[],Px),r4:Ve(z.hovercardShowUrls||[],Px),clickUrls:Ve(Q.loggingUrls||[],Px),visualElement:g.sn(z.trackingParams),productPrice:P,additionalFeesText:V,watchEndpoint:D||null}},CwV=function(N,z){var v={startMs:Math.floor(Number(N.startMs)),
impressionUrls:Ve(N.impressionUrls||[],Px),elements:Ve(N.elements||[],function(R,C){return Ry8(z,R,C)})};
N.trackingParams&&(v.visualElement=g.sn(N.trackingParams));return v},ZUE=function(N){g.GI.call(this,N);
this.N=this.endscreen=null;this.W={};this.G={};this.B=this.Z=null;this.Y=[];this.V=null;this.qd=!0;this.L=0;N=N.D();this.J=g.Pi(N)||g.SP(N);this.events=new g.VV(this);g.b(this,this.events);this.events.S(this.player,g.R2("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.C7("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.wW);this.events.S(window,"focus",this.cTT);this.load();var z=g.wL("STYLE");(g.tj("HEAD")[0]||document.body).appendChild(z);this.addOnDisposeCallback(function(){g.Ct(z)});
z.sheet&&(z.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),z.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},YWw=function(N){return N.player.getVideoData().hd?"current":N.J?"new":"current"},Sg=function(N){return N.player.D().playerStyle==="creator-endscreen-editor"},iUm=function(N){var z=N.player.getVideoData(),v=z.videoId;
N.N&&N.N.abort();v={method:"POST",onFinish:function(C){var Z=N.N=null;C.status===200&&(C=C.responseText,C.substring(0,3)===")]}"&&(C=C.substring(3),Z=JSON.parse(C),Z=CwV(Z,YWw(N))));Ee(N,Z)},
urlParams:{v:v},withCredentials:!0};N.J&&(v.urlParams.ptype="embedded");var R=z.kx;R&&(v.postParams={ad_tracking:R});if(z=g.xsK(z))if(z=g.uh(z),z=g.ON(z))N.N=g.Fb(z,v)},Ee=function(N,z,v){v=v===void 0?!0:v;
N.player.s6("creatorendscreen");N.Z&&(N.Z.dispose(),N.Z=null,N.B.dispose(),N.B=null);for(var R=g.f(Object.values(N.W)),C=R.next();!C.done;C=R.next())C.value.dispose();N.W={};N.G={};N.Y.length>0&&(N.Y.forEach(function(Q){Q.dispose()}),N.Y.length=0);
N.V&&(g.jW(N.V,"ytp-ce-element-show"),N.V.setAttribute("aria-hidden","true"));N.L=0;if((N.endscreen=z)&&z.elements){v&&j18(N);v=[];R=new g.zt(z.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});v.push(R);N.player.D().W||(N.Z=new g.X({K:"div",U:"ytp-ce-shadow"}),g.PX(N.player,N.Z.element,4),N.B=new g.zX(N.Z,200));for(R=0;R<z.elements.length;++R){C=z.elements[R];var Z=as$(N,C);if(Z){N.W[C.id]=Z;N.G[C.id]=C;g.PX(N.player,Z.element,4);var Y=new g.zt(C.startMs,C.endMs,{id:"ytp-ce-element-"+
C.id,namespace:"creatorendscreen"});v.push(Y);Q1Z(N,Z,C)}else g.PN(new g.XS("buildEndscreenElement null",C))}N.player.QT(v);N.wW()}},j18=function(N){var z=g.F8(),v=g.nz();
v&&z&&N.endscreen.visualElement&&g.qV(g.X8)(void 0,v,z,N.endscreen.visualElement)},as$=function(N,z){var v=null;
switch(z.type){case "VIDEO":N={K:"div",GU:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":z.l1||"","aria-hidden":"true"},j:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-covering-image",T:h$(z)},{K:"div",U:"ytp-ce-covering-shadow-top"},{K:"a",U:"ytp-ce-covering-overlay",T:{href:Hx(N,z.targetUrl),tabindex:"-1"},j:[{K:"div",GU:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.xe(z.title||"")},OT:z.title},{K:"div",U:z.dB?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
OT:z.videoDuration||void 0}]}]};v=new g.X(N);break;case "PLAYLIST":N={K:"div",GU:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":z.l1||"","aria-hidden":"true"},j:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-covering-image",T:h$(z)},{K:"div",U:"ytp-ce-covering-shadow-top"},{K:"a",U:"ytp-ce-covering-overlay",T:{href:Hx(N,z.targetUrl),tabindex:"-1"},j:[{K:"div",GU:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.xe(z.title||"")},OT:z.title},{K:"div",U:"ytp-ce-playlist-count",
j:[{K:"div",U:"ytp-ce-playlist-icon"},{K:"div",U:"ytp-ce-playlist-count-text",OT:z.playlistLength||void 0}]}]}]};v=new g.X(N);break;case "CHANNEL":v={K:"div",GU:["ytp-ce-element","ytp-ce-channel",z.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":z.l1||"","aria-hidden":"true"},j:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-expanding-overlay",j:[{K:"div",U:"ytp-ce-expanding-overlay-hider"},{K:"div",U:"ytp-ce-expanding-overlay-background"},{K:"div",U:"ytp-ce-expanding-overlay-content",
j:[{K:"div",U:"ytp-ce-expanding-overlay-body",j:[{K:"div",U:"ytp-ce-expanding-overlay-body-padding",j:[{K:"a",GU:["ytp-ce-channel-title","ytp-ce-link"],T:{href:Hx(N,z.targetUrl),target:"_blank",tabindex:"-1",dir:g.xe(z.title||"")},OT:z.title},z.subscribeButton?{K:"div",U:"ytp-ce-subscribe-container",j:[{K:"div",U:"ytp-ce-channel-subscribe"}]}:"",z.subscribersText?{K:"div",U:"ytp-ce-channel-subscribers-text",OT:z.subscribersText}:"",z.metadata?{K:"div",GU:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],OT:z.metadata}:""]}]}]}]},{K:"div",U:"ytp-ce-expanding-image",T:h$(z)}]};v=new g.X(v);var R=g.II(document,"div","ytp-ce-channel-subscribe",v.element)[0];if(z.subscribeButton&&z.channelId){g.Ye(R,"ytp-ce-subscribe-button");if(N.player.D().W){var C=null;var Z=z.sessionData.itct}else C="endscreen",Z=null;C=new g.uF(z.subscribeButton.subscribeText,z.subscribeButton.subscribeCount,z.subscribeButton.unsubscribeText,z.subscribeButton.unsubscribeCount,!!z.subscribeButton.enabled,!!z.subscribeButton.classic,
z.channelId,!!z.subscribeButton.subscribed,C,Z,N.player,!1);R.appendChild(C.element);N.Y.push(C)}break;case "WEBSITE":N={K:"div",GU:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":z.l1||"","aria-hidden":"true"},j:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-expanding-overlay",j:[{K:"div",U:"ytp-ce-expanding-overlay-hider"},{K:"div",U:"ytp-ce-expanding-overlay-background"},{K:"div",U:"ytp-ce-expanding-overlay-content",j:[{K:"div",U:"ytp-ce-expanding-overlay-body",j:[{K:"div",
U:"ytp-ce-expanding-overlay-body-padding",j:[{K:"div",U:"ytp-ce-website-title",T:{dir:g.xe(z.title||"")},OT:z.title},{K:"div",U:"ytp-ce-website-metadata",OT:z.metadata},{K:"a",GU:["ytp-ce-website-goto","ytp-ce-link"],T:{href:Hx(N,z.targetUrl),target:"_blank",tabindex:"-1"},OT:z.callToAction}]}]}]}]},{K:"div",U:"ytp-ce-expanding-image",T:h$(z)},{K:"div",U:"ytp-ce-expanding-icon",T:LD$(z.iconUrl)}]};v=new g.X(N);break;case "CREATOR_MERCHANDISE":v="",z.productPrice&&(v={K:"div",U:"ytp-ce-merchandise-price-container",
j:[{K:"div",U:"ytp-ce-merchandise-price",OT:z.productPrice}]},z.additionalFeesText&&v.j.push({K:"div",U:"ytp-ce-merchandise-additional-fees",OT:z.additionalFeesText})),N={K:"div",GU:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":z.l1||"","aria-hidden":"true"},j:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-expanding-overlay",j:[{K:"div",U:"ytp-ce-expanding-overlay-hider"},{K:"div",U:"ytp-ce-expanding-overlay-background"},{K:"div",U:"ytp-ce-expanding-overlay-content",
j:[{K:"div",U:"ytp-ce-expanding-overlay-body",j:[{K:"div",U:"ytp-ce-expanding-overlay-body-padding",j:[{K:"div",U:"ytp-ce-merchandise-title",T:{dir:g.xe(z.title||"")},OT:z.title},v,{K:"div",U:"ytp-ce-merchandise-metadata",OT:z.metadata},{K:"a",GU:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:Hx(N,z.targetUrl),target:"_blank",tabindex:"-1"},OT:z.callToAction}]}]}]}]},{K:"div",U:"ytp-ce-expanding-image",T:h$(z)},{K:"div",U:"ytp-ce-merchandise-invideo-cta-container",j:[{K:"div",U:"ytp-ce-merchandise-invideo-cta",
OT:z.callToAction||void 0}]}]},v=new g.X(N)}z.isPlaceholder&&g.Ye(v.element,"ytp-ce-placeholder");return v},h$=function(N){if(N.xD)var z=N.xD.thumbnails;
return LD$(z?z[z.length-1].url:null)},LD$=function(N){return N?{style:"background-image: url("+N+")"}:{}},Q1Z=function(N,z,v){function R(L){L&&(z.listen("blur",function(){L.style.display!="none"&&N.qd&&L.focus()}),z.S(L,"focus",Z),z.S(L,"blur",Y))}
function C(L){N.L+=L;N.L>0?(g.Ye(z.element,"ytp-ce-force-expand"),on(N,v.id,!0)):(g.jW(z.element,"ytp-ce-force-expand"),g.jW(z.element,"ytp-ce-element-hover"),on(N,v.id,!1))}
function Z(){C(1)}
function Y(){C(-1)}
z.listen("mouseenter",function(){KDl(N,z,v)});
z.listen("mouseleave",function(){lsm(N,z,v)});
N.player.D().W||z.listen("click",function(){g.Ye(z.element,"ytp-ce-element-hover")});
z.listen("click",function(L){WDw(N,v,L)});
z.listen("keypress",function(L){WDw(N,v,L)});
z.listen("focus",function(){KDl(N,z,v)});
z.listen("blur",function(){lsm(N,z,v)});
z.listen("touchstart",function(){KDl(N,z,v)});
var Q=g.XD("ytp-ce-expanding-overlay-hider",z.element);Q&&z.S(Q,"touchstart",function(L){L.stopPropagation();g.jW(z.element,"ytp-ce-element-hover");g.jW(z.element,"ytp-ce-force-expand")});
z.listen("keydown",function(L){N.qd=L.keyCode===9&&!L.shiftKey});
R(g.XD("ytp-sb-subscribe",z.element));R(g.XD("ytp-sb-unsubscribe",z.element));z.listen("focus",Z);z.listen("blur",Y)},WDw=function(N,z,v){if(z.targetUrl&&(!v||v.type!=="keypress"||v.keyCode===13)){for(var R=v.target;R&&!g.Zd(R,"ytp-ce-element");){g.Zd(R,"subscribe-label")&&GVP(N,z);
if(g.Zd(R,"ytp-ce-channel-subscribe"))return;R=R.parentElement||null}if(!R||g.Zd(R,"ytp-ce-element-hover")){v.preventDefault();v.stopPropagation();if(R=N.W[z.id])lsm(N,R,z),R.element.blur();if(v.ctrlKey||v.metaKey||z.tNp==="new")GVP(N,z),N.player.sendVideoStatsEngageEvent(17,void 0),N.player.pauseVideo(),v=g.uh(Hx(N,z.targetUrl)),v=g.ON(v),g.tX(v,void 0,z.sessionData);else{var C=g.ci(N.player.D())||N.player.getVideoData().hd,Z=function(){var Y=Hx(N,z.targetUrl),Q=z.sessionData,L=z.watchEndpoint,K=
g.R0(Y);C&&K&&(K.v||K.list)?N.player.n4(K.v,Q,K.list,!1,void 0,L||void 0):g.b4(Y,Q)};
GVP(N,z,function(){N.player.sendVideoStatsEngageEvent(17,Z)})}}}},Hx=function(N,z){N=N.player.D();
if(z){if(z.startsWith("//"))return N.protocol+":"+z;if(z.startsWith("/"))return g.Rm(N)+z}else return"";return z},KDl=function(N,z,v){g.Zd(z.element,"ytp-ce-element-hover")||(v.type==="VIDEO"||v.type==="PLAYLIST"?g.Ye(z.element,"ytp-ce-element-hover"):N.player.D().W?(new g.cn(function(){g.Ye(z.element,"ytp-ce-element-hover")},200)).start():g.Ye(z.element,"ytp-ce-element-hover"),D6(N,v.r4),on(N,v.id,!0))},lsm=function(N,z,v){g.jW(z.element,"ytp-ce-element-hover");
g.jW(z.element,"ytp-ce-force-expand");on(N,v.id,!1)},on=function(N,z,v){N.Z&&(v?N.B.show():N.B.hide());
for(var R=g.f(Object.keys(N.W)),C=R.next();!C.done;C=R.next())C=C.value,C!==z&&g.QY(N.W[C].element,"ytp-ce-element-shadow-show",v)},D6=function(N,z,v){function R(){Z||(C++,C===z.length&&(Y.stop(),v&&v()))}
if(!z||z.length===0||Sg(N))v&&v();else{z=xGU(N,z);var C=0,Z=!1,Y=new g.cn(function(){Z=!0;v&&v()},1E3,N);
Y.start();for(N=0;N<z.length;N++)g.Hd(z[N],R)}},GVP=function(N,z,v){D6(N,z.clickUrls,v);
(N=g.nz())&&z.p6&&g.Z9(N,z.visualElement)},xGU=function(N,z){var v=N.player.getVideoData().clientPlaybackNonce;
N=N.player.getCurrentTime().toFixed(2);v={CPN:v,AD_CPN:v,MT:N};N=[];for(var R=0;R<z.length;R++)N.push(eyU(z[R],v));return N},eyU=function(N,z){return N.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(v){var R=unescape(v);
R=R.substring(1,R.length-1);return z[R]?escape(z[R]):v})},JDV=function(N){return typeof N==="string"?N:""},bo=function(N,z,v){for(var R in z)if(z[R]===N)return N;
return v},yDm=function(N,z,v,R){this.value=N;
this.target=z;this.showLinkIcon=v;this.V=R},t$=function(N){return N.value?N.value:null},Oe=function(N){if(!N)return null;
var z=g.uh(JDV(N.value));z=g.ON(z);if(!z)return null;var v=bo(N.target,fsZ,"current");if(v==null)N=null;else{var R=N.show_link_icon;N=new yDm(z,v,R==="true"||R==="false"?R==="true":!0,N.pause_on_navigation!=null?N.pause_on_navigation:!0)}return N},dGm=function(N,z,v){this.type=N;
this.trigger=z;this.url=v},FD1=function(N){if(!N)return null;
var z=bo(N.type,s1E),v=bo(N.trigger,TGr);N=N.url;N=Array.isArray(N)&&N.length?N[0]:N;N=Oe(N?N:null);return z?new dGm(z,v,N):null},nbW=function(N,z,v,R,C){this.id=N;
this.type=z;this.style=v;this.data=C;this.action=R||[]},mG$=function(N,z){return g.G1(N.action,z)},$Gl=function(N,z){this.context=N;
this.V=z},UGw=function(N){return N.customMessage?In("div","iv-card-message",N.customMessage):""},XL=function(N,z){N="background-image: url("+N+");";
var v=[];z&&v.push(z);return{K:"div",U:"iv-card-image",T:{style:N},j:v}},BG9=function(N){if(!N.metaInfo||N.metaInfo.length===0)return"";
var z=[];N=g.f(N.metaInfo);for(var v=N.next();!v.done;v=N.next())z.push(In("li","",v.value));return{K:"ul",U:"iv-card-meta-info",j:z}},In=function(N,z,v){z?typeof z==="string"?z={"class":z}:Array.isArray(z)&&(z={"class":z.join(" ")}):z={};
z.dir=g.xe(v);return{K:N,T:z,OT:v}},ADw=function(N){if(!N.customMessage)return"";
var z=["iv-card-action","iv-card-primary-link"],v={};N.EX&&(z.push("iv-card-action-icon"),v.style="background-image: url("+N.EX+");");v.dir=g.xe(N.customMessage);var R=[{K:"span",OT:N.customMessage}];N.showLinkIcon&&(R.push("\u00a0"),R.push({K:"span",U:"iv-card-link-icon"}));return{K:"div",GU:z,T:v,j:R}},rz=function(N,z,v,R){if(R){z=g.f(z);
for(var C=z.next();!C.done;C=z.next())N.V(C.value,R,v.id,v.sessionData,v.kK.click,5)}},gbV=function(N,z){this.merchant=N;
this.price=z},pJ1=function(N){var z;
(z=N)&&!(z=N.length>1?N.charAt(0)==="/"&&N.charAt(1)!=="/":N==="/")&&(z=N.replace(/^(https?:)?\/\//,"").split("/",1),z=!z||z.length<1||!z[0]?[]:z[0].toLowerCase().split(".").reverse(),z=z[0]==="com"&&z[1]==="youtube"||z[0]==="be"&&z[1]==="youtu");return z?N.indexOf("/redirect?")===-1:!1},kVr=function(N,z){return z?z:pJ1(N)?"current":"new"},uo=function(N,z){g.H.call(this);
var v=this;this.element=N;this.context=z;this.kJ=!1;this.S8=new Map;this.vL=new Map;this.context.C.addEventListener(g.R2("annotations_module"),function(R){(R=v.S8.get(R))&&R.apply(v)});
this.context.C.addEventListener(g.C7("annotations_module"),function(R){(R=v.vL.get(R))&&R.apply(v)})},cx=function(N,z,v,R,C,Z,Y){N.context.V.listen(z,"click",function(Q){N.RJ(v,R,C,Z||[],Y||0,Q)});
N.context.V.listen(z,"touchstart",function(){N.kJ=!1});
N.context.V.listen(z,"touchmove",function(){N.kJ=!0})},PwW=function(N){var z;
return((z=g.t(N,g.SJ))==null?0:z.url)?g.t(N,g.SJ).url:(N=g.t(N,g.wi))&&N.videoId?(z="/watch?v="+N.videoId,N.playlistId&&(z+="&list="+N.playlistId),N.index&&(z+="&index="+N.index),N.startTimeSeconds&&(z+="&t="+N.startTimeSeconds),z):null},qS=function(N,z,v){return{z1:(N.impressionLoggingUrlsV2s||[]).map(function(R){return R.baseUrl||""}),
click:(v.loggingUrls||[]).map(function(R){return R.baseUrl||""}),
close:(z.dismissLoggingUrlsV2s||[]).map(function(R){return R.baseUrl||""}),
N5:(z.impressionLoggingUrlsV2s||[]).map(function(R){return R.baseUrl||""}),
h$:(z.clickLoggingUrlsV2s||[]).map(function(R){return R.baseUrl||""})}},VL9=function(N,z,v){uo.call(this,z,v);
var R=this;this.C=N;this.eventId=null;this.zE=this.tO=this.CV=this.Z=this.isInitialized=!1;this.cards=[];this.gW=this.Y=this.Id=this.B=this.UT=this.V=null;this.qd=[];this.Vp=this.L=this.E9=this.Rd=null;this.G=0;this.K0=new g.cn(function(){},v.iS.Et?4E3:3E3);
g.b(this,this.K0);this.ET=new g.cn(function(){});
g.b(this,this.ET);this.PL=new $Gl(v,function(C,Z,Y,Q,L,K){cx(R,C,Z,Y,Q,L,K)});
this.J=new g.X({K:"div",U:"iv-drawer",T:{id:"iv-drawer"},j:[{K:"div",U:"iv-drawer-header",T:{"aria-role":"heading"},j:[{K:"span",U:"iv-drawer-header-text"},{K:"button",GU:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{K:"div",U:"iv-drawer-content"}]});g.b(this,this.J);this.N=this.J.element;this.xT=new g.zX(this.J,330);g.b(this,this.xT);this.A0=g.XD("iv-drawer-header-text",this.N);this.W=g.XD("iv-drawer-content",this.N);this.addCueRange(0,v.videoData.lengthSeconds*
1E3,"",function(){R.CV&&MS(R,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(R.CV=R.Z)&&wz(R)});
this.BL=new g.VV(this);g.b(this,this.BL);this.C.addEventListener("videodatachange",this.HW.bind(this))},SWr=function(N,z){z=z.data;
z.autoOpenMs&&N.addCueRange(z.autoOpenMs,0x8000000000000,"",function(){MS(N,"YOUTUBE_DRAWER_AUTO_OPEN")});
z.autoCloseMs&&N.addCueRange(z.autoCloseMs,0x8000000000000,"",function(){wz(N)});
var v=z.headerText;g.YS(N.A0,v);N.Y&&N.Y.setAttribute("title",v);z.eventId&&(N.eventId=z.eventId);N.Rd=g.sn(z.trackingParams);N.L=g.sn(z.closeTrackingParams);N.E9=g.sn(z.iconTrackingParams)},Eb5=function(N,z){var v=z.cardId?z.cardId:"cr:"+N.G,R=N.C.D().experiments.j8("enable_error_corrections_infocard_web_client");
if(!z.content&&z.teaser.simpleCardTeaserRenderer&&R){var C=z.teaser.simpleCardTeaserRenderer,Z=z.icon?z.icon.infoCardIconRenderer:null;z={id:v,timestamp:N.G,type:"simple",teaserText:g.xt(C.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,sessionData:{},sponsored:!1,kK:{},DX:null,xK:C.trackingParams?g.sn(C.trackingParams):null,E9:Z&&Z.trackingParams?g.sn(Z.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
EX:null,title:"",customMessage:"",url:null,onClickCommand:C.onTapCommand||null};Nd(N,z)}else{var Y;if((Y=z.content)==null?0:Y.simpleCardContentRenderer){if(!z.cueRanges.length)return;Z=(C=z.content)==null?void 0:C.simpleCardContentRenderer;C=z.teaser.simpleCardTeaserRenderer;var Q=z.icon?z.icon.infoCardIconRenderer:null;z={id:v,timestamp:N.G,type:"simple",teaserText:g.xt(C.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,
sessionData:zC(N,v,z,Z),sponsored:!1,kK:qS(Z,C,Z.command),DX:Z.trackingParams?g.sn(Z.trackingParams):null,xK:C.trackingParams?g.sn(C.trackingParams):null,E9:Q&&Q.trackingParams?g.sn(Q.trackingParams):null,imageUrl:vC(Z.image.thumbnails,290).url,displayDomain:Z.displayDomain?g.xt(Z.displayDomain):null,showLinkIcon:!!Z.showLinkIcon,EX:null,title:Z.title?g.xt(Z.title):"",customMessage:Z.callToAction?g.xt(Z.callToAction):"",url:g.t(Z.command,g.SJ).url?Oe({pause_on_navigation:!N.context.videoData.isLivePlayback,
target:"new",value:g.t(Z.command,g.SJ).url}):null,onClickCommand:null};Nd(N,z)}else{var L;if((L=z.content)==null?0:L.collaboratorInfoCardContentRenderer){if(!z.cueRanges.length)return;C=(Z=z.content)==null?void 0:Z.collaboratorInfoCardContentRenderer;Z=z.teaser.simpleCardTeaserRenderer;Q=z.icon?z.icon.infoCardIconRenderer:null;z={id:v,timestamp:N.G,type:"collaborator",teaserText:g.xt(Z.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),startMs:Number(z.cueRanges[0].startCardActiveMs),
autoOpen:!!z.autoOpen,sessionData:zC(N,v,z,C),sponsored:!1,kK:qS(C,Z,C.endpoint),DX:C.trackingParams?g.sn(C.trackingParams):null,xK:Z.trackingParams?g.sn(Z.trackingParams):null,E9:Q&&Q.trackingParams?g.sn(Q.trackingParams):null,channelId:g.t(C.endpoint,g.Fe).browseId,customMessage:C.customText?g.xt(C.customText):null,profileImageUrl:vC(C.channelAvatar.thumbnails,290).url,title:C.channelName?g.xt(C.channelName):"",metaInfo:[C.subscriberCountText?g.xt(C.subscriberCountText):""],url:Oe({pause_on_navigation:!N.context.videoData.isLivePlayback,
target:"new",value:g.t(C.endpoint,g.Fe).canonicalBaseUrl?g.t(C.endpoint,g.Fe).canonicalBaseUrl:"/channel/"+g.t(C.endpoint,g.Fe).browseId}),onClickCommand:null};Nd(N,z)}else{var K;if((K=z.content)==null?0:K.playlistInfoCardContentRenderer){if(!z.cueRanges.length)return;C=(Q=z.content)==null?void 0:Q.playlistInfoCardContentRenderer;Z=z.teaser.simpleCardTeaserRenderer;Q=z.icon?z.icon.infoCardIconRenderer:null;z={id:v,timestamp:N.G,type:"playlist",teaserText:g.xt(Z.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),
startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,sessionData:zC(N,v,z,C),sponsored:!1,kK:qS(C,Z,C.action),DX:C.trackingParams?g.sn(C.trackingParams):null,xK:Z.trackingParams?g.sn(Z.trackingParams):null,E9:Q&&Q.trackingParams?g.sn(Q.trackingParams):null,YQ:vC(C.playlistThumbnail.thumbnails,258).url,customMessage:C.customMessage?g.xt(C.customMessage):null,playlistVideoCount:g.xt(C.playlistVideoCount),title:C.playlistTitle?g.xt(C.playlistTitle):"",metaInfo:[C.channelName?g.xt(C.channelName):
"",C.videoCountText?g.xt(C.videoCountText):""],url:Oe({pause_on_navigation:!N.context.videoData.isLivePlayback,target:"new",value:PwW(C.action)}),onClickCommand:null};Nd(N,z)}else{var l;if((l=z.content)==null?0:l.videoInfoCardContentRenderer){if(!z.cueRanges.length)return;var W;C=(W=z.content)==null?void 0:W.videoInfoCardContentRenderer;Z=z.teaser.simpleCardTeaserRenderer;Q=z.icon?z.icon.infoCardIconRenderer:null;z={id:v,timestamp:N.G,type:"video",teaserText:g.xt(Z.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),
startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,sessionData:zC(N,v,z,C),sponsored:!1,kK:qS(C,Z,C.action),DX:C.trackingParams?g.sn(C.trackingParams):null,xK:Z.trackingParams?g.sn(Z.trackingParams):null,E9:Q&&Q.trackingParams?g.sn(Q.trackingParams):null,YQ:vC(C.videoThumbnail.thumbnails,258).url,videoDuration:C.lengthString?g.xt(C.lengthString):null,customMessage:C.customMessage?g.xt(C.customMessage):null,title:C.videoTitle?g.xt(C.videoTitle):"",metaInfo:[C.channelName?g.xt(C.channelName):
"",C.viewCountText?g.xt(C.viewCountText):""],isLiveNow:!!C.badge,url:Oe({pause_on_navigation:!N.context.videoData.isLivePlayback,target:"new",value:PwW(C.action)}),onClickCommand:null};Nd(N,z)}}}}}N.G++},vC=function(N,z){for(var v=-1,R=-1,C=0;C<N.length;C++){if(N[C].height===z||N[C].width===290)return N[C];
((N[C].height||0)<z||(N[C].width||0)<290)&&(v<0||(N[v].height||0)<(N[C].height||0)||(N[v].width||0)<(N[C].width||0))?v=C:((N[C].height||0)>=z||(N[C].width||0)>=290)&&(R<0||(N[R].height||0)>(N[C].height||0)||(N[R].width||0)>(N[C].width||0))&&(R=C)}return N[R>=0?R:v]},zC=function(N,z,v,R){return{feature:v.feature?v.feature:"cards",
src_vid:N.context.videoData.videoId,annotation_id:z,ei:N.context.videoData.eventId||"",itct:R.trackingParams||""}},HU8=function(N,z){if(z=hy8(N,z))z===N.V&&(N.V=null),N.C.removeCueRange(z.jr.id),g.Ct(z.F0),g.fm(N.cards,z),N.rr(),RC(N)},MS=function(N,z,v){if(!N.Z){N.xT.show();
N.UT=new g.cn(function(){g.Ye(N.context.C.getRootNode(),g.cM.IV_DRAWER_OPEN)},0);
N.UT.start();N.BL.S(N.W,"mousewheel",function(Y){N.K0.start();Y.preventDefault();Y=Y||window.event;var Q=0;Y.type=="MozMousePixelScroll"?Q=0==(Y.axis==Y.HORIZONTAL_AXIS)?Y.detail:0:window.opera?Q=Y.detail:Q=Y.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?Y.wheelDeltaY/-30:Y.wheelDeltaY/-1.2:Y.wheelDelta/-1.6:Y.wheelDeltaY/-3;if(Y=Q)N.W.scrollTop+=Y});
N.Z=!0;var R=g.nz();R&&N.Rd&&N.L&&g.R$(R,[N.Rd,N.L]);z={TRIGGER_TYPE:z};for(var C=g.f(N.cards),Z=C.next();!Z.done;Z=C.next())Z=Z.value,Z.P6||(Z.P6=!0,obW(N.context.logger,Z.jr.kK.z1,z)),R&&g.R$(R,[Z.jr.DX]);$h(N.C);v&&(N.B=new g.cn(function(){N.Id=N.Y;N.gW.focus()},330),N.B.start())}},wz=function(N){N.Z&&(N.xT.hide(),g.Be(N.BL),g.jW(N.context.C.getRootNode(),g.cM.IV_DRAWER_OPEN),N.Z=!1,$h(N.C),N.B&&N.B.stop(),N.B=new g.cn(function(){N.Id&&(N.Id.focus(),N.Id=null)},330),N.B.start())},DG7=function(N){g.iP(N.Nu(),
[g.cM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.PX(N.C,N.N,5);N.Tc();N.Y=g.XD("ytp-cards-button",N.C.getRootNode());N.gW=g.XD("iv-drawer-close-button",N.N);N.isInitialized=!0},bUV=function(N){N.qd.push(g.C1("iv-teaser-shown",N.jU,N));
N.qd.push(g.C1("iv-teaser-hidden",N.Ts,N));N.qd.push(g.C1("iv-teaser-clicked",N.Dj,N));N.zE=!0},tLW=function(N,z){var v;
return z.onClickCommand&&((v=g.t(z.onClickCommand,g.fR5))==null?void 0:v.targetId)==="engagement-panel-error-corrections"?(N.Vp=z,!0):!1},OUr=function(N,z){N.Vp=z;
var v=N.C.getVideoData();if(!v)return!1;v=g.$N(v);if(v==null?0:v.markersMap)for(var R,C=0;((R=v)==null?void 0:R.markersMap.length)>C;C++){var Z=void 0,Y=(Z=v)==null?void 0:Z.markersMap[C];if(Y.key==="ERROR_CORRECTION_MARKERS"&&(Z=void 0,(Y=(Z=Y.value)==null?void 0:Z.markers)&&Y.length>0))return R=void 0,z.startMs=((R=g.t(Y[0],g.Wyf))==null?void 0:R.timeRangeStartMillis)||0,N.Vp=null,!0}return!1},Nd=function(N,z){if(!tLW(N,z)||OUr(N,z)){var v=IsE(N,z);
if(v){var R={jr:z,F0:v.element,P6:!1};if(z.onClickCommand)N.C.X("web_infocards_teaser_show_logging_fix")&&(N.zE||bUV(N),HU8(N,z.id),v=N.findLastIndex(R),g.UZ(N.cards,v,0,R));else{N.isInitialized||DG7(N);HU8(N,z.id);var C=N.findLastIndex(R);g.UZ(N.cards,C,0,R);v.Nd(N.W,C);N.rr()}z.autoOpen?N.addCueRange(z.startMs,0x8000000000000,z.id,function(){N.Z||(N.V=R,RC(N),XJ8(N,R),MS(N,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(v=N.context.C.getCurrentTime()*1E3,v<5E3&&v>z.startMs&&rD$(N,R),N.addCueRange(z.startMs,
z.startMs+1,z.id,function(){rD$(N,R)}),RC(N))}}},IsE=function(N,z){switch(z.type){case "simple":N=N.PL;
var v=z.displayDomain?{K:"div",U:"iv-card-image-text",OT:z.displayDomain}:void 0;var R=ADw(z);v={K:"div",GU:["iv-card"],j:[{K:"a",U:"iv-click-target",T:{href:z.url?t$(z.url)||"":""},j:[XL(z.imageUrl,v),{K:"div",U:"iv-card-content",j:[In("h2",void 0,z.title),R]}]}]};v=new g.X(v);rz(N,g.OC("iv-click-target",v.element),z,z.url);z=v;break;case "collaborator":N=N.PL;v={K:"div",GU:["iv-card","iv-card-channel"],j:[{K:"a",GU:["iv-click-target"],T:{href:t$(z.url)||"","data-ytid":z.channelId},j:[XL(z.profileImageUrl),
{K:"div",U:"iv-card-content",j:[UGw(z),{K:"h2",U:"iv-card-primary-link",OT:z.title},BG9(z)]}]}]};v=new g.X(v);rz(N,g.OC("iv-click-target",v.element),z,z.url);z=v;break;case "playlist":N=N.PL;v={K:"div",GU:["iv-card","iv-card-playlist"],j:[{K:"a",U:"iv-click-target",T:{href:t$(z.url)||""},j:[XL(z.YQ,{K:"div",U:"iv-card-image-overlay",j:[{K:"span",U:"iv-card-playlist-video-count",OT:z.playlistVideoCount}]}),{K:"div",U:"iv-card-content",j:[UGw(z),In("h2","iv-card-primary-link",z.title),BG9(z)]}]}]};
v=new g.X(v);rz(N,g.OC("iv-click-target",v.element),z,z.url);z=v;break;case "productListing":N=N.PL;var C=z.offers.length!=0;v=["iv-card"];R="";var Z=ADw(z);C&&(v.push("iv-card-product-listing"),R="iv-card-primary-link",Z=z.offers[0],C=[],Z.price&&C.push({K:"div",U:"iv-card-offer-price",OT:Z.price}),Z.merchant&&C.push({K:"div",U:"iv-card-offer-merchant",OT:Z.merchant}),Z={K:"div",j:C});C=z.url?t$(z.url)||"":"";v={K:"div",GU:v,T:{tabindex:"0"},j:[{K:"a",GU:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
z.imageUrl+");",href:C,"aria-hidden":"true",tabindex:"-1"}},{K:"div",U:"iv-card-content",j:[z.sponsored?{K:"div",U:"iv-card-sponsored",j:["Sponsored",{K:"div",U:"iv-ad-info-container",j:[{K:"div",U:"iv-ad-info",OT:"{{adInfo}}"},{K:"div",U:"iv-ad-info-icon-container",j:[{K:"div",U:"iv-ad-info-icon"},{K:"div",U:"iv-ad-info-callout"}]}]}]}:"",{K:"a",U:"iv-click-target",T:{href:C},j:[In("h2",R,z.title),Z]}]}]};v=new g.X(v);R=g.wL("span");g.YS(R,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
v.Qy(R,"adInfo");rz(N,g.OC("iv-click-target",v.element),z,z.url);z=v;break;case "video":N=N.PL;R=z.videoDuration?{K:"span",U:"iv-card-video-duration",OT:z.videoDuration}:void 0;Z=z.isLiveNow?{K:"span",GU:["yt-badge","yt-badge-live"],OT:"LIVE NOW"}:null;C={K:"div",GU:["iv-card","iv-card-video"],j:[{K:"a",U:"iv-click-target",T:{href:((v=z.url)==null?void 0:t$(v))||""},j:[XL(z.YQ,R),{K:"div",U:"iv-card-content",j:[UGw(z),In("h2","iv-card-primary-link",z.title),BG9(z),Z]}]}]};v=new g.X(C);rz(N,g.OC("iv-click-target",
v.element),z,z.url);z=v;break;default:return null}return z},uv9=function(N){if(N.V)return N.V.jr.type==="productListing";
if(N.C.X("enable_wn_infocards")){var z;return!((z=N.cards)==null||!z.length)&&g.Iz(N.cards,function(v){return v.jr.type==="productListing"})}return g.Iz(N.cards,function(v){return v.jr.type==="productListing"})},RC=function(N){g.QY(N.C.getRootNode(),"ytp-cards-shopping-active",uv9(N))},rD$=function(N,z){if(!g.Zd(N.C.getRootNode(),"ytp-cards-teaser-shown")){if(N.V!==z){var v=g.nz(),R=N.V?N.V.jr.E9:N.E9;
v&&R&&g.CK(v,[R]);N.V=z;RC(N)}if(v=N.isInitialized)v=N.Nu().style.display=="none";v||(v=N.context.C.getPlayerState(),R=v===0&&N.context.C.getCurrentTime()===0,v=!(v===1||v===3||R));v||z.jr.teaserDurationMs&&N.C.uU(!0,{teaserText:z.jr.teaserText,durationMs:z.jr.teaserDurationMs,onClickCommand:z.jr.onClickCommand});N.ET.isActive()||((!N.Z||!N.K0.isActive()&&N.tO)&&XJ8(N,z),N.ET.start(910+z.jr.teaserDurationMs))}},XJ8=function(N,z){N.J.Vh?(z=new pQ([0,
N.W.scrollTop],[0,z.F0.offsetTop],600,zyl),N.context.Z.listen(z,"animate",function(v){N.W.scrollTop=v.y}),N.context.Z.listen(z,"finish",function(v){N.W.scrollTop=v.y}),z.play()):(N.J.iF(!0),N.W.scrollTop=z.F0.offsetTop,N.J.iF(!1))},CD=function(N){return N.V&&N.V.jr?N.V.jr:N.cards[0]&&N.cards[0].jr?N.cards[0].jr:null},hy8=function(N,z){return g.G1(N.cards,function(v){return v.jr.id===z})},Zh=function(N,z,v){uo.call(this,N,z);
this.annotation=v;this.isActive=!1},cDZ=function(N){var z=N.annotation.data;
"start_ms"in z&&"end_ms"in z&&N.addCueRange(Number(z.start_ms),Number(z.end_ms),N.annotation.id,function(){N.show()},function(){N.hide()})},YB=function(N,z,v){Zh.call(this,N,z,v);
this.W=null;this.L=!1;this.Z=null;this.N=!1;this.V=this.G=this.B=null},qWV=function(N,z){var v=v===void 0?0:v;
var R=IQl(z).width;g.bm(z,R);v=new wV$(z,[R,z.offsetTop],[R-R-v,z.offsetTop],200,NGZ);g.b(N,v);N.context.Z.listen(v,"begin",function(){g.um(z,!0)});
v.play()},N4r=function(N,z){if(z.channel_name){var v=N.createElement({K:"div",
GU:["iv-branding-context-name"],OT:z.channel_name}),R=N.createElement({K:"div",GU:["iv-branding-context-subscribe"]}),C=z.standalone_subscribe_button_data;C&&(N.V=new g.uF(C.subscribeText,C.subscribeCount,C.unsubscribeText,C.unsubscribeCount,!!C.enabled,!!C.classic,z.channel_id,!!C.subscribed,C.feature,z.session_data.itct,N.context.C,!1),N.V.Nd(R));var Z=N.createElement({K:"div",GU:["iv-branding-context-subscribe-caret"]}),Y=N.createElement({K:"div",GU:["branding-context-container-inner"]});Y.appendChild(Z);
Y.appendChild(v);Y.appendChild(R);g.um(Y,!1);var Q=N.createElement({K:"div",GU:["branding-context-container-outer"]});Q.appendChild(Y);g.SB(Q,"right",z.image_width+"px");g.zP(N.Nu(),Q);N.Z=new g.cn(function(){ML1(N,Y,Q)},500);
g.b(N,N.Z);N.context.V.listen(N.Nu(),"mouseover",function(){wJW(N,Y,Q,Z,z.image_height)});
N.context.V.listen(N.Nu(),"mouseout",function(){N.Z.start()})}},wJW=function(N,z,v,R,C){N.Z.stop();
if(!N.N){var Z=g.rv(z);N.V||(z.style.width=g.D8(Z.width,!0),v.style.width=g.D8(Z.width,!0));g.SB(R,"top",Z.height-Math.max(Math.min(Z.height,C)/2+10,20)+"px");g.SB(R,"right","1px");N.N=!0;g.um(z,!0);N.B=new g.cn(function(){g.Ye(this.Nu(),"iv-branding-active")},0,N);
N.B.start()}},ML1=function(N,z,v){g.jW(N.Nu(),"iv-branding-active");
N.G=new g.cn(function(){g.um(z,!1);N.V||(v.style.width=g.D8(0,!0))},250);
N.G.start();N.N=!1},zOZ=function(N,z,v,R,C,Z,Y){this.V=N;
this.Z=z;this.iS=v;this.videoData=R;this.logger=C;this.C=Z;this.W=Y},vRZ=function(N,z,v){Zh.call(this,N,z,v);
var R=this;this.Y=this.isCollapsed=this.J=!1;this.G=5E3;this.W=this.Z=this.V=this.N=null;this.L=this.createElement({K:"div",GU:["iv-promo-contents"]});this.B=new g.cn(function(){R.V.setAttribute("aria-hidden","true");g.um(R.Z,!1);g.um(R.W,!0)},700,this);
g.b(this,this.B)},CY8=function(N){var z=N.annotation.data;
if(N.annotation.style==="cta")var v=6;else if(N.annotation.style==="video"||N.annotation.style==="playlist")v=7;N.G=z.collapsedelay_ms||N.G;var R=["iv-promo","iv-promo-inactive"];N.Nu().setAttribute("aria-hidden","true");N.Nu().setAttribute("aria-label","Promotion");N.Nu().tabIndex=0;var C=N.annotation.IP(),Z=z.image_url;if(Z){var Y=N.createElement({K:"div",GU:["iv-promo-img","iv-click-target"]});Z=N.createElement({K:"img",T:{src:Z,"aria-hidden":"true"}});Y.appendChild(Z);z.video_duration&&!z.is_live?
(Z=N.createElement({K:"span",U:"iv-promo-video-duration",OT:z.video_duration}),Y.appendChild(Z)):z.playlist_length&&(Z=N.createElement({K:"span",U:"iv-promo-playlist-length",OT:z.playlist_length.toString()}),Y.appendChild(Z));C&&cx(N,Y,C,N.annotation.id,z.session_data,void 0,v)}C?(Z=N.createElement({K:"a",U:"iv-promo-txt"}),g.q8(Z,t$(C)),N.V=Z):N.V=N.createElement({K:"div",U:"iv-promo-txt"});switch(N.annotation.style){case "cta":case "website":var Q=N.createElement({K:"p",j:[{K:"strong",OT:z.text_line_1}]});
var L=N.createElement({K:"p",j:[{K:"span",U:"iv-promo-link",OT:z.text_line_2}]});if(Z=z.text_line_3){R.push("iv-promo-website-card-cta-redesign");var K=N.createElement({K:"button",GU:["iv-promo-round-expand-icon","ytp-button"]});Z=N.createElement({K:"button",GU:["iv-button","iv-promo-button"],j:[{K:"span",U:"iv-button-content",OT:Z}]});var l=N.createElement({K:"div",U:"iv-promo-button-container"});l.appendChild(Z);C&&cx(N,N.Nu(),C,N.annotation.id,z.session_data,void 0,v)}g.Ye(N.V,"iv-click-target");
C&&cx(N,N.V,C,N.annotation.id,z.session_data,void 0,v);break;case "playlist":case "video":Q=N.createElement({K:"p",j:[{K:"span",OT:z.text_line_1}]}),L=N.createElement({K:"p",j:[{K:"strong",OT:z.text_line_2}]}),z.is_live&&(Q=L,L=N.createElement({K:"span",GU:["yt-badge","iv-promo-badge-live"],OT:"LIVE NOW"})),g.Ye(N.V,"iv-click-target"),C&&cx(N,N.V,C,N.annotation.id,z.session_data,void 0,v),R.push("iv-promo-video")}Q&&N.V.appendChild(Q);L&&N.V.appendChild(L);N.L.appendChild(N.V);l&&N.L.appendChild(l);
v=N.createElement({K:"div",U:"iv-promo-actions"});N.W=N.createElement({K:"button",GU:["iv-promo-expand","ytp-button"]});N.W.title="Expand";N.context.V.listen(N.W,"click",function(W){ROl(N,5E3,W)});
v.appendChild(N.W);g.um(N.W,!1);N.context.V.listen(N.Nu(),"mouseover",N.Yt,N);N.context.V.listen(N.Nu(),"mouseout",N.fY,N);N.context.V.listen(N.Nu(),"touchend",function(W){ROl(N,5E3,W)});
N.Z=N.createElement({K:"button",GU:["iv-promo-close","ytp-button"]});N.Z.title="Close";N.context.V.listen(N.Z,"click",N.annotation.style==="cta"&&z.text_line_3?N.le:N.SP,N);v.appendChild(N.Z);g.iP(N.Nu(),R);Y&&(g.zP(N.Nu(),Y),K&&Y.appendChild(K));g.zP(N.Nu(),N.L);g.zP(N.Nu(),v)},ROl=function(N,z,v){v.stopPropagation();
Zy7(N);Yk7(N,z);N.V.focus()},iyP=function(N){N.isCollapsed||N.Y||N.N||(g.Ye(N.Nu(),"iv-promo-collapsed"),N.isCollapsed=!0,N.B.start())},Zy7=function(N){N.B.stop();
N.isCollapsed&&(g.aO(N.Nu(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),N.isCollapsed=!1,N.V&&N.V.removeAttribute("aria-hidden"),g.um(N.W,!1),g.um(N.Z,!0))},Yk7=function(N,z){N.N||(N.N=g.hL(function(){jdW(this);
iyP(this)},z,N))},jdW=function(N){N.N&&(g.u7.clearTimeout(N.N),N.N=null)},aWE=function(N){this.C=N},obW=function(N,z,v){z&&(v?id(N,z.map(function(R){return g.pj(R,v)})):id(N,z))},id=function(N,z,v,R){var C=1,Z=void 0,Y=-1;
if(v){var Q=!1;Z=function(){C--;C||Q||(clearTimeout(Y),Q=!0,v())};
Y=setTimeout(function(){Q=!0;v()},1E3)}z=g.f(z||[]);
for(var L=z.next();!L.done;L=z.next())L=L.value,C++,g.Hd(L,Z);R&&(C++,R!==0&&N.C.sendVideoStatsEngageEvent(R,Z))},Qd7=function(N){g.GI.call(this,N);
var z=this;this.qd=this.Y=!1;this.loadNumber=0;this.G={};this.logger=new aWE(this.player);this.N=new g.VV(this);this.B=this.L=null;this.events=new g.VV(this);this.Vl=this.J=this.V=null;this.Vp=[];g.b(this,this.N);this.N.S(this.player,"onVideoAreaChange",function(){z.publish("onVideoAreaChange")});
this.N.S(this.player,"onHideControls",function(){z.publish("onHideControls")});
this.N.S(this.player,"onShowControls",function(){z.publish("onShowControls")});
this.N.S(this.player,"resize",function(R){z.publish("resize",R)});
this.N.S(this.player,"presentingplayerstatechange",function(R){z.publish("presentingplayerstatechange",R)});
this.subscribe("presentingplayerstatechange",this.QK,this);this.subscribe("resize",this.Wf,this);this.player.D().tO.subscribe("vast_info_card_add",this.H7,this);g.b(this,this.events);this.PL=this.createElement({K:"div",U:"video-custom-annotations"});this.W=new g.X({K:"div",GU:["ytp-player-content","ytp-iv-player-content"]});g.b(this,this.W);g.PX(this.player,this.W.element,4);this.W.hide();this.Z=new g.X({K:"div",GU:["ytp-iv-video-content"]});g.b(this,this.Z);N=this.createElement({K:"div",U:"video-annotations"});
N.appendChild(this.PL);this.Z.element.appendChild(N);this.gt()&&this.load();var v=this.createElement({K:"style"});(g.tj("HEAD")[0]||document.body).appendChild(v);this.addOnDisposeCallback(function(){g.Ct(v)});
if(N=v.sheet)N.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),N.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),N.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),N.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),N.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),N.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),N.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),N.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),N.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),N.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},LgZ=function(N){N=N.createElement({K:"div",
GU:["annotation","annotation-type-custom"]});g.um(N,!1);return N},KgW=function(N,z){z=!z.isCued()&&!g.u(z,1024);
N.W.iF(z);N.Z.iF(z)},lWm=function(N,z,v){N.Y=!0;
N.B=g.Fb(z,v)},Wg5=function(N,z){for(var v={},R=g.f(z.attributes),C=R.next();!C.done;C=R.next())C=C.value,v[C.name]=C.nodeValue;
for(R=0;R<z.childNodes.length;R++)if(C=z.childNodes[R],g.v$(C)&&C.nodeType==1){if(v[C.tagName])var Z=v[C.tagName];else if(C.tagName==="data"){C.childNodes.length>0&&(Z=C.childNodes[0].nodeValue,v[C.tagName]=typeof Z==="string"?Z.trim():Z);continue}else Z=[],v[C.tagName]=Z;C&&C.tagName==="TEXT"?C.childNodes.length===1&&C.childNodes[0].nodeType===3?Z.push(C.childNodes[0].nodeValue):Z.push(""):C&&Z.push(Wg5(N,C))}return v},JE1=function(N){var z=g.h(N.player.getVideoData());
if(z.UT){var v=N.player.D().tO.get(z.videoId);if(v){var R={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(C,Z,Y){C=N.loadNumber;Z=z.videoId;N.loaded&&N.loadNumber===C&&N.player.getVideoData().videoId===Z&&(Y=g.lQ(Y)&&Y.responseXML?Y.responseXML:null)&&G0U(N,Y)}};
g.zJ()&&(R.onFinish=xbU(N,R.onFinish));R.postParams={ic_only:"1"};eOE(R,v);N.Y=!0;g.Fb(z.UT,R)}}},eOE=function(N,z){N.method="POST";
N.postParams=N.postParams||{};z.Kg&&(N.postParams.ic_coll=z.Kg);z.uC&&(N.postParams.ic_xml=z.uC);z.LQ&&(N.postParams.ic_track=z.LQ)},yE5=function(N){var z=new g.X({K:"div"});
g.um(z.element,!1);var v=new VL9(N.player,z.element,jm(N));g.b(v,z);z.Nd(N.W.element);v.pM();return v},db7=function(N,z){var v,R;
if(z=(v=z.getWatchNextResponse())==null?void 0:(R=v.cards)==null?void 0:R.cardCollectionRenderer)N.qd=!0,fW9(N,z),z.headerText&&N.Vl&&(v=g.xt(z.headerText),N.Vl.setAttribute("title",v))},jm=function(N){if(!N.J){var z=new vb8(N);
g.b(N,z);var v=new g.ej(N);g.b(N,v);N.J=new zOZ(z,v,N.player.D(),N.player.getVideoData(),N.logger,N.player,N.gD)}return N.J},G0U=function(N,z){var v=!1,R=z.getElementsByTagName("annotations");
if(R&&!(R.length<1)&&(R=R[0].getAttribute("itct"))){var C=g.nz();if(C){var Z=g.F8();Z&&g.qV(g.I_)(void 0,C,Z,[g.sn(R)])}}z=z.getElementsByTagName("annotation");for(R=0;R<z.length;R++){Z=Wg5(N,z[R]);C=null;try{if(Z){var Y=Z.id,Q=/.+/;var L=typeof Y==="string"&&Q!=null&&Y!=null&&Y.match(Q)?Y:"";var K=bo(Z.type,sd8),l=bo(Z.style,T45),W=JDV(Z.data),G=W.length!==0?JSON.parse(W):{};var x=Z.action;Z=FD1;if(x==null)var e=null;else if(g.z1(x)){Q=[];for(var d=g.f(x),T=d.next();!T.done;T=d.next()){var m=Z(T.value);
m&&Q.push(m)}e=Q}else{var n=Z(x);e=n?[n]:[]}C=L&&K?new nbW(L,K,l,e,G):null}else C=null}catch(Rv){}if(C)if(C.type==="branding"||C.type==="promotion"){Z=N;Q=C;var P=LgZ(Z),V=null;switch(Q.type){case "branding":if(Z.player.D().Fy)break;Z.W.element.appendChild(P);V=new YB(P,jm(Z),Q);break;case "promotion":g.PX(Z.player,P,4),V=new vRZ(P,jm(Z),Q)}V&&V.pM();if(Z=V)g.b(N,Z),N.G[C.id]=Z}else if(C.type==="card"||C.type==="drawer"){N.V||(N.V=yE5(N),g.b(N,N.V));if(C.type==="card"){P=N.V;var D=(v=C)&&v.data&&
v.data.card_type;C=v.data;if(D)switch(Z=C.tracking||{},Z={z1:Z.impression,click:Z.click,close:Z.close,N5:Z.teaser_impression,h$:Z.teaser_click},Q=C.tracking_params||{},V=null,D){case "collaborator":v={id:v.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,kK:Z,DX:Q.card?g.sn(Q.card):null,xK:Q.teaser?g.sn(Q.teaser):null,E9:Q.icon?g.sn(Q.icon):
null,channelId:C.channel_id,customMessage:C.custom_message?C.custom_message:null,profileImageUrl:C.image_url,title:C.title,metaInfo:C.meta_info,url:Oe({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url}),onClickCommand:null};Nd(P,v);break;case "playlist":v={id:v.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,kK:Z,
DX:Q.card?g.sn(Q.card):null,xK:Q.teaser?g.sn(Q.teaser):null,E9:Q.icon?g.sn(Q.icon):null,YQ:C.image_url,playlistVideoCount:C.playlist_video_count,customMessage:C.custom_message?C.custom_message:null,title:C.title,metaInfo:C.meta_info,url:g.h(Oe({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url})),onClickCommand:null};Nd(P,v);break;case "productListing":C.signin_url&&(V=Oe({target:"current",value:C.signin_url}));D=[];for(var c=C.offers||[],r=0;r<c.length;r++)D.push(new gbV(g.yp(c[r].merchant),
g.yp(c[r].price)));v={id:v.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,kK:Z,DX:Q.card?g.sn(Q.card):null,xK:Q.teaser?g.sn(Q.teaser):null,E9:Q.icon?g.sn(Q.icon):null,imageUrl:C.image_url,displayDomain:C.display_domain?C.display_domain:null,showLinkIcon:!!C.show_link_icon,EX:C.button_icon_url?C.button_icon_url:null,title:C.title,customMessage:C.custom_message?
C.custom_message:null,url:g.h(Oe({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url})),WzU:V,V08:C.signin_title?C.signin_title:void 0,qPd:C.signin_message?C.signin_message:void 0,offers:D,onClickCommand:null};Nd(P,v);break;case "simple":v={id:v.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,kK:Z,DX:Q.card?g.sn(Q.card):
null,xK:Q.teaser?g.sn(Q.teaser):null,E9:Q.icon?g.sn(Q.icon):null,imageUrl:C.image_url,displayDomain:C.display_domain?C.display_domain:null,showLinkIcon:!!C.show_link_icon,EX:C.button_icon_url?C.button_icon_url:null,title:C.title,customMessage:C.custom_message?C.custom_message:null,url:g.h(Oe({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url})),onClickCommand:null};Nd(P,v);break;case "video":v={id:v.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,
startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,kK:Z,DX:Q.card?g.sn(Q.card):null,xK:Q.teaser?g.sn(Q.teaser):null,E9:Q.icon?g.sn(Q.icon):null,YQ:C.image_url,videoDuration:C.video_duration||null,customMessage:C.custom_message?C.custom_message:null,title:C.title,metaInfo:C.meta_info,isLiveNow:!!C.is_live_now,url:g.h(Oe({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url})),onClickCommand:null},Nd(P,v)}}else SWr(N.V,C);v=!0}}v&&
($h(N.player),N.Wf())},fW9=function(N,z){var v=!1;
N.V||(N.V=yE5(N),g.b(N,N.V));for(var R=g.f(z.cards||[]),C=R.next();!C.done;C=R.next())C=C.value,C.cardRenderer&&(Eb5(N.V,C.cardRenderer),v=!0);if(v){var Z;(Z=N.player.getVideoData())!=null&&g.gw(Z)||(v=N.V,R=z.headerText?g.xt(z.headerText):"",g.YS(v.A0,R),v.Y&&v.Y.setAttribute("title",R),v.context.videoData.eventId&&(v.eventId=v.context.videoData.eventId),v.Rd=z.trackingParams?g.sn(z.trackingParams):null,v.L=z.closeButton.infoCardIconRenderer.trackingParams?g.sn(z.closeButton.infoCardIconRenderer.trackingParams):
null,v.E9=z.icon.infoCardIconRenderer.trackingParams?g.sn(z.icon.infoCardIconRenderer.trackingParams):null,N.Wf());$h(N.player)}},Fg1=function(N,z,v,R,C){if(!N.player.D().Fy){var Z=[];
z.navigationEndpoint&&g.t(z.navigationEndpoint,g.Fe)&&g.t(z.navigationEndpoint,g.Fe).browseId&&Z.push(new dGm("openUrl","click",new yDm("/channel/"+g.t(z.navigationEndpoint,g.Fe).browseId,"new",!0,!0)));var Y=z.watermark.thumbnails[0];R={channel_name:z.channelName,end_ms:z.endTimeMs,image_height:Y.height,image_type:1,image_url:Y.url,image_width:Y.width,is_mobile:!1,session_data:{annotation_id:v,ei:C,feature:"iv",itct:z.trackingParams,src_vid:R},start_ms:z.startTimeMs};if(z.subscribeButton&&g.t(z.subscribeButton,
g.ne)){R.channel_id=g.t(z.subscribeButton,g.ne).channelId;var Q;z=g.t(z.subscribeButton,g.ne);Y=C=null;z.subscribed?(z.subscriberCountWithUnsubscribeText&&(C=g.xt(z.subscriberCountWithUnsubscribeText)),z.subscriberCountText&&(Y=g.xt(z.subscriberCountText))):(z.subscriberCountText&&(C=g.xt(z.subscriberCountText)),z.subscriberCountWithSubscribeText&&(Y=g.xt(z.subscriberCountWithSubscribeText)));var L,K=((L=g.t((Q=z.signInEndpoint)==null?void 0:Q.commandMetadata,g.dF))==null?void 0:L.url)||"";Q={subscribeText:g.xt(z.unsubscribedButtonText),
subscribeCount:C||"",unsubscribeText:g.xt(z.subscribedButtonText),unsubscribeCount:Y||"",enabled:z.enabled||!1,classic:!1,subscribed:z.subscribed||!1,feature:"iv",signInUrl:K};R.standalone_subscribe_button_data=Q}Z=new nbW(v,"branding","branding",Z,R);Q=LgZ(N);N.W.element.appendChild(Q);Z=new YB(Q,jm(N),Z);Z.pM();g.b(Z,Z);N.G[v]=Z}},xbU=function(N,z){return function(){var v=g.SI.apply(0,arguments);
N.HL()||N.Vp.push(g.oH.Mo(function(){z.apply(null,g.U(v))}))}},nRm=function(N){return N==="annotation-editor"||N==="live-dashboard"};
g.mQ.prototype.uU=g.Ym(45,function(N,z){var v=g.Bb(this.eV());v&&v.uU(N,z)});
var Bx={},A$=null;g.Lm(pQ,g.L6);g.J=pQ.prototype;g.J.getDuration=function(){return this.duration};
g.J.play=function(N){if(N||this.V==0)this.progress=0,this.coords=this.W;else if(this.isPlaying())return!1;gz(this);this.startTime=N=g.jV();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.N=this.startTime;this.progress||this.D$();this.pX("play");this.isPaused()&&this.pX("resume");this.V=1;var z=g.Cm(this);z in Bx||(Bx[z]=this);ud$();c99(this,N);return!0};
g.J.stop=function(N){gz(this);this.V=0;N&&(this.progress=1);qLZ(this,this.progress);this.onStop();this.K9()};
g.J.pause=function(){this.isPlaying()&&(gz(this),this.V=-1,this.pX("pause"))};
g.J.AO=function(){this.V==0||this.stop(!1);this.pX("destroy");pQ.gi.AO.call(this)};
g.J.destroy=function(){this.dispose()};
g.J.KR=function(){this.pX("animate")};
g.J.pX=function(N){this.dispatchEvent(new MY9(N,this))};
g.Lm(MY9,g.q_);g.Lm(kh,pQ);kh.prototype.Z=function(){};
kh.prototype.KR=function(){this.Z();kh.gi.KR.call(this)};
kh.prototype.K9=function(){this.Z();kh.gi.K9.call(this)};
kh.prototype.D$=function(){this.Z();kh.gi.D$.call(this)};
g.Lm(wV$,kh);wV$.prototype.Z=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.y(vb8,g.H);g.J=vb8.prototype;g.J.listen=function(N,z,v,R){v=(0,g.Zl)(v,R||this.W);N=g.dY(N,z,v);this.V.push(N);return N};
g.J.Dw=function(N,z,v,R){v=(0,g.Zl)(v,R||this.W);N=XVl(N,z,v);this.V.push(N);return N};
g.J.Kb=function(N){g.T6(N);g.fm(this.V,N)};
g.J.removeAll=function(){g.T6(this.V);this.V.length=0};
g.J.AO=function(){this.removeAll();g.H.prototype.AO.call(this)};g.y(ZUE,g.GI);g.J=ZUE.prototype;g.J.load=function(){g.GI.prototype.load.call(this);if(!Sg(this)){var N=g.e0v(this.player.getVideoData());N?(N=CwV(N,YWw(this)),Ee(this,N,!1)):iUm(this)}};
g.J.unload=function(){Ee(this,null);this.N&&(this.N.abort(),this.N=null);g.GI.prototype.unload.call(this)};
g.J.mA=function(N,z){return Sg(this)?N==="loadCustomEndscreenRenderer"?(N=CwV(z,"new"),Ee(this,N),!0):null:null};
g.J.getOptions=function(){return Sg(this)?["loadCustomEndscreenRenderer"]:[]};
g.J.wW=function(){if(this.endscreen&&this.endscreen.elements){var N=this.player.getVideoContentRect();if(N&&N.width!==0&&N.height!==0){var z=this.player.getPlayerSize();if(z&&z.width!==0&&z.height!==0){var v=N.width/N.height;var R=0;for(var C=-1,Z=0;Z<mb9.length;Z++){var Y=Math.abs(z.width-mb9[Z]);if(C===-1||R>=Y)C=Z,R=Y}R=$b$[C];this.Z&&g.SB(this.Z.element,"outline-width",Math.max(z.width,z.height)+"px");for(z=0;z<this.endscreen.elements.length;++z)if(Z=this.endscreen.elements[z].id,C=this.W[Z],
Y=this.G[Z],C&&Y){var Q=Y.width*v/Y.aspectRatio,L=Math.round(Y.width*N.width);Z=Math.round(Q*N.height);var K=N.left+Math.round(Y.left*N.width),l=N.top+Math.round(Y.top*N.height);g.XM(C.element,L,Z);g.bm(C.element,K,l);g.aO(C.element,Ub7);L>256||Z>256?g.Ye(C.element,"ytp-ce-large-round"):L>96||Z>96?g.Ye(C.element,"ytp-ce-medium-round"):g.Ye(C.element,"ytp-ce-small-round");g.aO(C.element,B4V);L=Y.left+Y.width/2;Y=Y.top+Q/2;g.Ye(C.element,L<=.5&&Y<=.5?"ytp-ce-top-left-quad":L>.5&&Y<=.5?"ytp-ce-top-right-quad":
L<=.5&&Y>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.aO(C.element,$b$);g.Ye(C.element,R);(C=g.II(document,"div","ytp-ce-expanding-overlay-body",C.element)[0])&&g.SB(C,"height",Z+"px")}}}}};
g.J.onCueRangeEnter=function(N){if(this.endscreen)if(N.getId()==="ytp-ce-in-endscreen")D6(this,this.endscreen.impressionUrls),(N=g.nz())&&this.endscreen.visualElement&&g.vS(N,this.endscreen.visualElement),this.V&&(g.Ye(this.V,"ytp-ce-element-show"),this.V.removeAttribute("aria-hidden"),this.player.iG()?g.Ye(this.V,"ytp-ce-hide-button-lower"):g.jW(this.V,"ytp-ce-hide-button-lower"));else{N=N.getId().substring(15);var z=this.W[N],v=this.G[N];g.Ye(z.element,"ytp-ce-element-show");z.element.removeAttribute("aria-hidden");
z=this.player.getRootNode();g.Ye(z,"ytp-ce-shown");D6(this,v.impressionUrls);(z=g.nz())&&g.vS(z,v.visualElement);this.player.D().Y&&this.player.Qp("endscreenelementshown",N)}};
g.J.onCueRangeExit=function(N){if(N.getId()==="ytp-ce-in-endscreen")this.V&&(g.jW(this.V,"ytp-ce-element-show"),this.V.setAttribute("aria-hidden","true"));else{N=N.getId().substring(15);var z=this.W[N];g.jW(z.element,"ytp-ce-element-show");z.element.setAttribute("aria-hidden","true");z=this.player.getRootNode();g.jW(z,"ytp-ce-shown");this.player.D().Y&&this.player.Qp("endscreenelementhidden",N)}};
g.J.cTT=function(N){var z=this;N.target===window&&(new g.cn(function(){for(var v=g.f(Object.values(z.W)),R=v.next();!R.done;R=v.next())g.aO(R.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.J.iF=function(N){for(var z=g.f(Object.values(this.W)),v=z.next();!v.done;v=z.next())v=v.value,N?v.element.setAttribute("hidden",""):v.element.removeAttribute("hidden")};
g.J.fT0=function(N){this.V&&this.player.getRootNode().removeChild(this.V);N&&(g.Ye(N,"ytp-ce-hide-button-container"),this.V=N,g.PX(this.player,this.V,4))};
var mb9=[346,426,470,506,570,640,853,1280,1920],$b$="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),B4V=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Ub7=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var fsZ={ir8:"current",XWp:"new"};var s1E={CLOSE:"close",hO0:"openUrl",SUBSCRIBE:"subscribe"},TGr={FcU:"click",CLOSE:"close",k0p:"hidden",IoU:"rollOut",pZT:"rollOver",hoU:"shown"};nbW.prototype.IP=function(){var N=mG$(this,function(z){return z.type==="openUrl"&&z.url!=null});
return N?N.url:null};
var T45={f9O:"anchored",pz:"branding",CHANNEL:"channel",nGl:"cta",qbd:"highlightText",jTl:"label",PLAYLIST:"playlist",POPUP:"popup",QUL:"speech",SUBSCRIBE:"subscribe",q_T:"title",VIDEO:"video",fW1:"website"},sd8={pz:"branding",doU:"card",br1:"drawer",aJT:"highlight",AR1:"marker",V3p:"promotion",TEXT:"text",RZW:"widget"};g.y(uo,g.H);g.J=uo.prototype;g.J.addCueRange=function(N,z,v,R,C){N=new g.zt(N,z,{id:v,namespace:"annotations_module"});R&&this.S8.set(N,R);C&&this.vL.set(N,C);this.context.C.QT([N],1)};
g.J.pM=function(){this.context.W.subscribe("resize",this.rr,this)};
g.J.Nu=function(){return this.element};
g.J.RJ=function(N,z,v,R,C,Z){if(this.kJ)return!1;Z&&(Z.stopPropagation(),Z.preventDefault());this.navigate(N,v,R,C);return!1};
g.J.show=function(){};
g.J.hide=function(){};
g.J.destroy=function(){g.Ct(this.Nu())};
g.J.rr=function(){};
g.J.navigate=function(N,z,v,R){var C=this,Z=t$(N);if(Z){var Y=kVr(Z,N.target),Q=function(){N.V&&C.context.C.pauseVideo();var L=C.context.videoData.hd||!1,K=g.R0(Z||"");L&&K&&(K.v||K.list)?C.context.C.n4(K.v,z,K.list,!1):g.tX(Z||"",Y==="current"?"_top":void 0,z)};
Y==="new"&&(Q(),Q=null);id(this.context.logger,v,Q,R);pJ1(Z)||(v=g.nz(),R=z.itct,v&&R&&g.Z9(v,g.sn(R)))}};
g.J.AO=function(){this.S8.clear();this.vL.clear();g.H.prototype.AO.call(this)};
g.J.createElement=function(N){N=new g.X(N);g.b(this,N);return N.element};g.y(VL9,uo);g.J=VL9.prototype;g.J.HW=function(){this.Vp&&Nd(this,this.Vp)};
g.J.isAvailable=function(){var N;if(N=!!this.cards.length)(N=this.C.getRootNode())?(N=g.rv(N),N=173<N.width&&173<N.height):N=!1;return N};
g.J.rr=function(){var N=this.isAvailable();g.um(this.Nu(),N);g.QY(this.context.C.getRootNode(),g.cM.IV_DRAWER_ENABLED,N);$h(this.C)};
g.J.destroy=function(){this.C.uU(!1);try{this.C.getRootNode().removeChild(this.N)}catch(N){}g.ZK(this.qd);g.Be(this.BL);this.UT&&this.UT.dispose();this.B&&this.B.dispose();uo.prototype.destroy.call(this)};
g.J.Tc=function(){var N=this;this.context.V.listen(g.XD("iv-drawer-close-button",this.N),"click",this.Gm,this);this.context.V.listen(this.W,"touchend",function(){N.K0.start()});
this.context.V.listen(this.W,"scroll",this.JK,this);this.context.W.subscribe("onHideControls",function(){N.tO=!0});
this.context.W.subscribe("onShowControls",function(){N.tO=!1});
this.context.W.subscribe("onVideoAreaChange",function(){N.tO=g.Zd(N.C.getRootNode(),"ytp-autohide")});
this.qd.push(g.C1("iv-button-shown",this.vA,this));this.qd.push(g.C1("iv-button-hidden",this.Er,this));bUV(this)};
g.J.findLastIndex=function(N){if(this.cards.length===0)return 0;var z=g.eV(this.cards,function(v){return N.jr.startMs>v.jr.startMs||N.jr.startMs===v.jr.startMs&&N.jr.timestamp>=v.jr.timestamp?!0:!1});
return z===-1?0:z+1};
g.J.Gm=function(){if(this.Z){id(this.context.logger,CD(this).kK.close);var N=g.nz();N&&this.L&&g.Z9(N,this.L);wz(this)}};
g.J.JK=function(){g.QY(this.N,"iv-drawer-scrolled",this.W.scrollTop>0)};
g.J.vA=function(){var N=g.nz(),z=CD(this);z=z?z.E9:this.E9;N&&z&&g.R$(N,[z])};
g.J.Er=function(){var N=g.nz(),z=CD(this);z=z?z.E9:this.E9;N&&z&&g.CK(N,[z])};
g.J.jU=function(){var N=CD(this);id(this.context.logger,N.kK.N5);var z=g.nz();if(z&&N)if(this.C.X("web_infocards_teaser_show_logging_fix")){var v=[];N.xK&&v.push(N.xK);N.E9&&v.push(N.E9);v.length>0&&g.R$(z,v)}else g.R$(z,[N.xK,N.E9])};
g.J.Ts=function(){var N=g.nz(),z=CD(this);N&&z&&g.CK(N,[z.xK])};
g.J.Dj=function(N){var z=CD(this),v=g.nz();this.V?N?(N=this.context.logger,id(N,z.kK.h$),N.C.sendVideoStatsEngageEvent(4,void 0),v&&z.xK&&g.Z9(v,z.xK)):(N=this.context.logger,id(N,z.kK.h$),N.C.sendVideoStatsEngageEvent(4,void 0),v&&z.E9&&g.Z9(v,z.E9)):(N=this.context.logger,id(N,z.kK.h$),N.C.sendVideoStatsEngageEvent(4,void 0),v&&this.E9&&g.Z9(v,this.E9))};g.y(Zh,uo);Zh.prototype.pM=function(){uo.prototype.pM.call(this);cDZ(this)};
Zh.prototype.show=function(){uo.prototype.show.call(this);var N=g.nz(),z=this.annotation.data;N&&z&&(z=z.session_data)&&g.R$(N,[g.sn(z.itct)])};
Zh.prototype.hide=function(){uo.prototype.hide.call(this);var N=g.nz(),z=this.annotation.data;N&&z&&(z=z.session_data)&&g.CK(N,[g.sn(z.itct)])};g.y(YB,Zh);
YB.prototype.show=function(){if(!this.isActive){Zh.prototype.show.call(this);if(!this.L){g.Ye(this.Nu(),"iv-branding");var N=this.annotation.data;this.W=this.createElement({K:"img",GU:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:N.image_url,width:N.image_width,height:N.image_height}});g.um(this.W,!1);var z=this.createElement({K:"button",GU:["branding-img-container","ytp-button"]});z.appendChild(this.W);this.Nu().appendChild(z);var v=this.annotation.IP();v&&cx(this,z,
v,this.annotation.id,N.session_data);this.context.C.X("disable_branding_context")||N4r(this,N);this.L=!0}g.um(this.Nu(),!0);this.isActive=!0;if(this.W){try{qWV(this,this.W)}catch(R){}g.Ye(this.context.C.getRootNode(),"ytp-branding-shown");this.context.C.getRootNode().style.setProperty("--branding-image-width",this.W.getAttribute("width")+"px")}}};
YB.prototype.hide=function(){this.isActive&&(Zh.prototype.hide.call(this),g.um(this.Nu(),!1),this.isActive=!1,g.jW(this.context.C.getRootNode(),"ytp-branding-shown"))};
YB.prototype.destroy=function(){this.V&&(this.V.dispose(),this.V=null);g.jW(this.context.C.getRootNode(),"ytp-branding-shown");Zh.prototype.destroy.call(this)};g.y(vRZ,Zh);g.J=vRZ.prototype;g.J.show=function(){this.isActive||(Zh.prototype.show.call(this),this.J||(CY8(this),this.J=!0),g.um(this.Nu(),!0),g.hL(function(){g.jW(this.Nu(),"iv-promo-inactive")},100,this),this.Nu().removeAttribute("aria-hidden"),this.isActive=!0,jdW(this),Zy7(this),Yk7(this,this.G))};
g.J.hide=function(){this.isActive&&(g.Ye(this.Nu(),"iv-promo-inactive"),this.isActive=!1,this.Nu().setAttribute("aria-hidden","true"))};
g.J.RJ=function(N,z,v,R,C,Z){return this.isCollapsed?!1:Zh.prototype.RJ.call(this,N,z,v,R,C,Z)};
g.J.Yt=function(N){this.Y=!0;ROl(this,500,N)};
g.J.fY=function(){this.Y=!1;iyP(this)};
g.J.SP=function(N){N.stopPropagation();this.hide()};
g.J.le=function(N){N.stopPropagation();jdW(this);this.isCollapsed=!0;g.Ye(this.Nu(),"iv-promo-collapsed-no-delay");this.B.start()};
g.J.destroy=function(){this.B.dispose();Zh.prototype.destroy.call(this)};g.y(Qd7,g.GI);g.J=Qd7.prototype;g.J.mA=function(N,z){if(!nRm(this.player.D().playerStyle))return null;switch(N){case "loadCustomAnnotationsXml":return(N=g.q7(z))&&G0U(this,N),!0;case "removeCustomAnnotationById":return z&&this.V&&(HU8(this.V,z),$h(this.player)),!0}return null};
g.J.getOptions=function(){return nRm(this.player.D().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.J.gt=function(){var N=this.player.D(),z=g.h(this.player.getVideoData()),v=N.annotationsLoadPolicy||z.annotationsLoadPolicy;return g.z8(z)||this.player.isMutedByEmbedsMutedAutoplay()?!1:v===1&&!z.b0||N.tO.get(z.videoId)||g.pe(z)||g.k6(z)?!0:!1};
g.J.Wf=function(){if(this.Z){var N=this.player.n0().getVideoContentRect(!0);g.XM(this.Z.element,N.width,N.height);g.bm(this.Z.element,N.left,N.top)}if(this.V){var z=this.player.IB();N=this.V;z=z.width;g.QY(N.N,"iv-drawer-small",z<=426);g.QY(N.N,"iv-drawer-big",z>=1280)}};
g.J.QK=function(N){KgW(this,N.state);g.u(N.state,2)&&(this.iG()&&this.yF()&&this.player.getPresentingPlayerType()!==2&&this.Sb(!1),this.uU(!1))};
g.J.load=function(){function N(Y){var Q=z.loadNumber;z.B=null;z.loaded&&z.loadNumber===Q&&z.player.getVideoData().videoId===R&&(Y=g.lQ(Y)&&Y.responseXML?Y.responseXML:null)&&(G0U(z,Y),g.Ye(z.player.getRootNode(),"iv-module-loaded"))}
var z=this;g.GI.prototype.load.call(this);KgW(this,this.player.getPlayerStateObject());this.loadNumber++;var v=g.h(this.player.getVideoData()),R=v.videoId;g.zJ()&&(N=xbU(this,N));var C={format:"XML",onFinish:N,onError:function(){z.B=null},
urlParams:{}};v.isPharma&&(C.urlParams.pharma="1");C.method="POST";C.withCredentials=!0;var Z=this.player.D().tO.get(R);Z&&eOE(C,Z);Z=Z&&(Z.uC||Z.Kg);if(!v.cm||Z)v.UT?lWm(this,v.UT,C):(this.L=function(){if(!z.Y)z.onVideoDataChange(C);var Y=g.h(z.player.getVideoData());(Y==null?0:g.gw(Y))&&!z.qd&&db7(z,Y)},this.player.addEventListener("videodatachange",this.L));
g.PX(this.player,this.Z.element,4);this.Wf();(Z=g.pe(v))&&fW9(this,Z);(Z=g.k6(v))&&Z.featuredChannel&&Fg1(this,Z.featuredChannel,Z.annotationId||"branding",v.videoId||null,v.eventId||null);this.Vl=g.XD("ytp-cards-button",this.player.getRootNode());g.gw(v)&&db7(this,v)};
g.J.onVideoDataChange=function(N){var z=g.h(this.player.getVideoData());z.UT&&lWm(this,z.UT,N)};
g.J.unload=function(){this.player.s6("annotations_module");for(var N=g.f(Object.keys(this.G)),z=N.next();!z.done;z=N.next())this.G[z.value].destroy();this.J=null;this.V&&(this.V.destroy(),this.V=null,$h(this.player));this.Y=!1;this.B&&(this.B.abort(),this.B=null);this.qd=!1;this.G={};this.W.hide();g.GI.prototype.unload.call(this);this.Z.detach();this.L&&(this.player.removeEventListener("videodatachange",this.L),this.L=null)};
g.J.H7=function(N){N===this.player.getVideoData().videoId&&(this.loaded?JE1(this):this.load())};
g.J.iG=function(){var N;return((N=this.V)==null?void 0:N.isAvailable())||this.qd};
g.J.yF=function(){return!!this.V&&this.V.Z};
g.J.Sb=function(N,z,v){z=z===void 0?!1:z;this.iG();this.V&&(N?v?MS(this.V,v,z):MS(this.V,"YOUTUBE_DRAWER_AUTO_OPEN",z):wz(this.V))};
g.J.uU=function(N,z){this.player.publish(N?"cardsteasershow":"cardsteaserhide",z)};
g.J.AO=function(){this.player.D().tO.unsubscribe("vast_info_card_add",this.H7,this);g.jW(this.player.getRootNode(),g.cM.IV_DRAWER_OPEN);for(var N=this.Vp,z=g.oH,v=0,R=N.length;v<R;v++)z.gG(N[v]);this.Vp.length=0;g.GI.prototype.AO.call(this)};
g.J.createElement=function(N){N=new g.X(N);g.b(this,N);return N.element};g.Wb("annotations_module",Qd7);g.Wb("creatorendscreen",ZUE);})(_yt_player);
