(function(g){var window=this;'use strict';var KAP=function(N,z){if(!Number.isFinite(N))return String(N);N=String(N);var v=N.indexOf(".");v===-1&&(v=N.length);var R=N[0]==="-"?"-":"";R&&(N=N.substring(1));return R+(0,g.fu5)("0",Math.max(0,z-v))+N},lHr=function(){return{K:"svg",
T:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},j:[{K:"path",T:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},WA1=function(){return{K:"svg",
T:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},j:[{K:"path",T:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},xWP=function(N){typeof N==="number"?(this.date=Gcw(N,0,1),Tw(this,1)):g.v$(N)?(this.date=Gcw(N.getFullYear(),N.getMonth(),N.getDate()),Tw(this,N.getDate())):(this.date=new Date(g.jV()),N=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),Tw(this,N))},Gcw=function(N,z,v){z=new Date(N,z,v);
N>=0&&N<100&&z.setFullYear(z.getFullYear()-1900);return z},Tw=function(N,z){N.getDate()!=z&&N.date.setUTCHours(N.date.getUTCHours()+(N.getDate()<z?1:-1))},Fw=function(N,z){g.D2.call(this,N,{K:"div",
U:"ytp-reminder-menu",T:{role:"menu",tabindex:"-1"},j:[{K:"div",U:"ytp-reminder-menu-contents",j:[{K:"div",U:"ytp-reminder-menu-items"}]}]},100,!0);this.V=z;this.Z=[];this.menuPopupRenderer=void 0;this.items=this.e8("ytp-reminder-menu-items");this.hide()},eVV=function(N){return(N.menuPopupRenderer&&N.menuPopupRenderer.items||[]).reduce(function(z,v){v&&v.menuServiceItemRenderer&&z.push(v.menuServiceItemRenderer);
return z},[])},no=function(N){g.X.call(this,{K:"div",
j:[{K:"button",GU:["ytp-offline-slate-button","ytp-button"],j:[{K:"div",U:"ytp-offline-slate-button-icon",OT:"{{icon}}"},{K:"div",U:"ytp-offline-slate-button-text",OT:"{{text}}"}]}]});this.C=N;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.W=void 0;this.N=this.V=null;(this.G=this.e8("ytp-offline-slate-button"))&&this.S(this.G,"click",this.L);this.hide()},yF$=function(N,z,v){!N.toggleButtonRenderer&&z&&z.toggleButtonRenderer?N.toggleButtonRenderer=z.toggleButtonRenderer:
z&&z.toggleButtonRenderer||(N.toggleButtonRenderer=null);
!N.upcomingEventReminderButtonRenderer&&v&&g.t(v,JF$)?N.upcomingEventReminderButtonRenderer=g.t(v,JF$):v&&g.t(v,JF$)||(N.upcomingEventReminderButtonRenderer=null);m0(N)},m0=function(N){if(N.toggleButtonRenderer){var z=N.toggleButtonRenderer;
if(z.isToggled){var v=z.toggledText?g.xt(z.toggledText):"";N.update({text:v,icon:fH1(z.toggledIcon)})}else v=z.defaultText?g.xt(z.defaultText):"",N.update({text:v,icon:fH1(z.defaultIcon)});N.show()}else N.upcomingEventReminderButtonRenderer?(z=dW9(N))?(v=z.text?g.xt(z.text):"",N.update({text:v,icon:fH1(z.icon)}),N.show()):N.hide():N.hide()},TPV=function(N,z,v){N.N||(N.N=new g.Mf(N.C.D().yE));
var R={context:g.Qi(N.N.config_||g.aq())};g.nz()&&(R.context.clientScreenNonce=g.nz());R.params=v;g.w5(N.N,z,R,{timeout:5E3,onSuccess:function(){N.upcomingEventReminderButtonRenderer&&N.W&&(N.upcomingEventReminderButtonRenderer.currentState=N.W,N.W=void 0)},
onError:function(){s65(N)},
onTimeout:function(){s65(N)}})},s65=function(N){N.toggleButtonRenderer?(N.toggleButtonRenderer.isToggled=!N.toggleButtonRenderer.isToggled,m0(N)):N.upcomingEventReminderButtonRenderer&&(N.W=void 0,m0(N))},fH1=function(N){if(!N)return null;
switch(N.iconType){case "NOTIFICATIONS":return lHr();case "NOTIFICATIONS_NONE":return WA1();case "NOTIFICATIONS_ACTIVE":return g.Fo();default:return null}},dW9=function(N){if(!N.upcomingEventReminderButtonRenderer)return null;
var z=N.W||N.upcomingEventReminderButtonRenderer.currentState;N=g.f(N.upcomingEventReminderButtonRenderer.states||[]);for(var v=N.next();!v.done;v=N.next())if((v=g.t(v.value,FAZ))&&v.state===z&&v.button&&g.t(v.button,g.E9))return g.t(v.button,g.E9);return null},nKP=function(N){g.X.call(this,{K:"div",
U:"ytp-offline-slate",j:[{K:"div",U:"ytp-offline-slate-background"},{K:"div",U:"ytp-offline-slate-bar",j:[{K:"span",U:"ytp-offline-slate-icon",j:[{K:"svg",T:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},j:[{K:"path",T:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{K:"circle",T:{cx:"12",cy:"12",r:"3"}}]}]},{K:"span",U:"ytp-offline-slate-messages",j:[{K:"div",U:"ytp-offline-slate-main-text",T:{"aria-label":"{{label}}"},OT:"{{mainText}}"},{K:"div",U:"ytp-offline-slate-subtitle-text",OT:"{{subtitleText}}"}]},{K:"span",U:"ytp-offline-slate-buttons"}]},{K:"button",GU:["ytp-offline-slate-close-button","ytp-button"],j:[g.fK()]},{K:"button",GU:["ytp-offline-slate-open-button","ytp-button"],j:[g.yr()]}]});var z=this;this.api=N;this.V=this.W=null;this.background=this.e8("ytp-offline-slate-background");
this.Z=this.e8("ytp-offline-slate-bar");this.G=new g.cn(function(){g.Ye(z.Z,"ytp-offline-slate-bar-fade")},15E3);
this.L=!1;this.N=new g.cn(function(){g.Ye(z.element,"ytp-offline-slate-collapsed")},15E3);
g.b(this,this.N);g.b(this,this.G);this.countdownTimer=new g.cn(this.wp,1E3,this);this.S(N,"presentingplayerstatechange",this.Tv);this.S(N,"livestatedata",this.FW);this.S(this.e8("ytp-offline-slate-close-button"),"click",function(){g.Ye(z.element,"ytp-offline-slate-collapsed")});
this.S(this.e8("ytp-offline-slate-open-button"),"click",function(){g.jW(z.element,"ytp-offline-slate-collapsed")});
this.hide();N=this.getVideoData();N.getPlayerResponse()&&(N=g.h(N.getPlayerResponse()).playabilityStatus)&&this.FW(N);N=this.api.getPresentingPlayerType()===8&&!this.getVideoData().V6;var v=this.api.getPresentingPlayerType()===8;g.QY(this.element,"ytp-offline-slate-premiere-trailer",N);g.QY(this.element,"ytp-offline-slate-hide-background",v)},mWU=function(N,z,v){if(z){var R=z.subtitleText!=null?g.xt(z.subtitleText):"";
v=v?v:z.mainText!=null?g.xt(z.mainText):"";var C,Z,Y,Q;z=(Q=(C=z.mainText)==null?void 0:(Z=C.accessibility)==null?void 0:(Y=Z.accessibilityData)==null?void 0:Y.label)!=null?Q:v;N.update({mainText:v,subtitleText:R,label:z});g.QY(N.element,"ytp-offline-slate-single-text-line",!R);g.QY(N.Z,"ytp-offline-slate-bar-hidden",!v&&!R)}},$v=function(N,z){var v=(0,g.I)();
this.trigger=N;this.V=z;this.Z=v},pTr=function(N){g.GI.call(this,N);
var z=this;this.L=!1;this.Y=0;this.B=!1;this.W=new g.cn(function(){$Wl(z)},0);
this.V=this.heartbeatParams=null;this.N=!1;this.G=new g.h_(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.qd=new g.Mf(void 0);this.attestationResponse=Promise.resolve(void 0);this.J=Promise.resolve(void 0);this.utcOffsetMinutes=-(new xWP).getTimezoneOffset();this.Z=new g.VV(this);g.b(this,this.W);g.b(this,this.Z);UWr(this);BP7(this);this.Z.S(N,"heartbeatparams",this.sS);this.Z.S(N,"presentingplayerstatechange",this.Z3);this.Z.S(N,"videoplayerreset",this.Nn);this.Z.S(N,g.R2("heartbeat"),
this.onCueRangeEnter);this.N&&this.V&&AF$(this,void 0,this.V);var v=new g.zt(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),R=new g.zt(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});N.QT([v,R]);gKm(this)},gKm=function(N){var z=N.getVideoData();
!z.X("use_rta_for_player")&&z.Jx&&(z=z.botguardData)&&g.Dv(z,N.player.D())},kcr=function(N){var z,v;
return g.S(function(R){if(R.W==1)return g.k(R,g.dqO(),2);if(!R.V)return N.sequenceNumber>=3?R.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):R.return(void 0);z=N.getVideoData();v={};return R.return(g.fKx((v.cpn=z.clientPlaybackNonce,v.encryptedVideoId=z.videoId||"",v),1500))})},UWr=function(N){var z=N.getVideoData();
if(z.Jx)if(z.X("use_rta_for_player"))N.attestationResponse=kcr(N);else if(z=new g.AY7(z),g.hG.isInitialized()||N.sequenceNumber>=3){var v=Promise,R=v.resolve,C=null;if(z.videoData.Ml){var Z=g.gVK(z);if(Z){C={};var Y={};Z=Z.split("&");Z=g.f(Z);for(var Q=Z.next();!Q.done;Q=Z.next())Q=Q.value.split("="),Q.length===2&&(Y[Q[0]]=Q[1]);Y.r1a&&(C.webResponse=Y.r1a);Y.r1c&&(C.error=P_8[Number(Y.r1c)]);C.challenge=z.videoData.Ml}}N.attestationResponse=R.call(v,C||void 0)}},VN$=function(N){var z=N.getVideoData();
if(!g.yO(N.getVideoData())||z.Ep)return!1;if(z.B){N=z.B.flavor==="playready"&&z.X("html5_innertube_heartbeats_for_playready");var v=z.B.flavor==="widevine"&&z.X("html5_innertube_heartbeats_for_widevine");z=g.Iy(z.B)&&z.X("html5_innertube_heartbeats_for_fairplay");return!(N||v||z)}return!0},SJ$=function(N){if(VN$(N))return!!N.heartbeatParams;
var z=N.getVideoData();return!g.yO(N.getVideoData())||z.Eb||z.pI?!!z.heartbeatToken:!1},Ua=function(N,z){if(!N.W.isActive()&&N.L){var v=N.getVideoData();
if(SJ$(N)||v.isLivePlayback){if(z===void 0)if(N.B)if(N.N)z=7500;else{var R;z=((R=N.heartbeatParams)==null?0:R.interval)?N.heartbeatParams.interval*1E3:N.getVideoData().Sm||6E4}else z=1E3;N.W.start(z)}}},oKP=function(N,z,v){z.Mk&&(v=g.kS(v,{internalipoverride:z.Mk}));
var R={cpn:z.clientPlaybackNonce};z.contextParams&&(R.context_params=z.contextParams);z.c5&&(R.kpt=z.c5);v=g.kS(v,R);g.Fb(v,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(C){if(!N.W.isActive()&&BF(N)){N.G.reset();N.sequenceNumber++;C=C.responseText;var Z=EKw(C);if(Z){N.player.Qp("onHeartbeat",Z);var Y=Z.status==="ok"?Z.stop_heartbeat?2:0:Z.status==="stop"?1:Z.status==="live_stream_offline"?0:-1}else Y=(Y=C.match(hVw))?Y[1]==="0"?0:1:-1;Hcm(N,void 0,Z,C,Y)}},
onError:function(C){BF(N)&&AP(N,!0,"net-"+C.status)},
onTimeout:function(){BF(N)&&AP(N,!0,"timeout")},
withCredentials:!0})},$Wl=function(N){var z,v;
g.S(function(R){z=N.player.D();v=N.getVideoData();if(!BF(N))return R.return();if(VN$(N))return DW1(N,z,v),R.Zp(0);UWr(N);return g.k(R,bc7(N,z,v),0)})},DW1=function(N,z,v){var R;
if((R=N.heartbeatParams)!=null&&R.url){var C=g.kS(N.heartbeatParams.url,{request_id:g.s0_()});v.Rd&&(C=g.kS(C,{vvt:v.Rd}),v.mdxEnvironment&&(C=g.kS(C,{mdx_environment:v.mdxEnvironment})));g.CW(z,v.oauthToken).then(function(Z){Z&&(C=g.kS(C,{access_token:Z}));oKP(N,v,C)})}},BF=function(N){var z=N.getVideoData();
return N.player.getPresentingPlayerType()===3||g.u(N.player.getPlayerStateObject(N.getPlayerType()),4)?!1:SJ$(N)||z.isLivePlayback?!0:(g7(N),!1)},bc7=function(N,z,v){var R,C,Z,Y,Q,L,K,l,W,G,x,e,d,T,m,n,P,V,D,c;
return g.S(function(r){if(r.W==1)return R="player/heartbeat",Z={videoId:v.videoId,sequenceNumber:N.sequenceNumber,heartbeatServerData:(C=N.Vp)!=null?C:v.heartbeatServerData},N.J=N.attestationResponse,v.Jx?g.k(r,N.J,3):r.Zp(2);r.W!=2&&(Z.attestationResponse=r.V);Y=g.Z2(v);L=(Q=Y.client)!=null?Q:{};L.utcOffsetMinutes=N.utcOffsetMinutes;Z.context=Y;Z.cpn=v.clientPlaybackNonce;if(K=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)L.timeZone=K;l={heartbeatChecks:[]};
if(W=v.getPlayerResponse())v.heartbeatToken&&(Z.heartbeatToken=v.heartbeatToken),(G=W.playabilityStatus)&&(x=G.liveStreamability)&&x.liveStreamabilityRenderer&&l.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");v.heartbeatToken&&l.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.TW(z)&&(l.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),e=tNU(N),d={},e!==null&&(d.clientPlayerPositionUtcMillis=e),m=(T=N.player.eV())==null?void 0:g.$D(T),P=((n=m)==null?void 0:n.freePreviewWatchedDuration)||
0,P>0&&(d.freePreviewWatchedDuration={seconds:""+P}),l.unpluggedParams=d);Z.heartbeatRequestParams=l;v.isLivePlayback?(V=tNU(N),V!==null&&(Z.playbackState||(Z.playbackState={}),Z.playbackState.playbackPosition={utcTimeMillis:V})):z.X("enable_heartbeat_vod_playback_position")&&(D=Oc1(N),D!==null&&(Z.playbackState||(Z.playbackState={}),Z.playbackState.playbackPosition={streamTimeMillis:D}));N.player.publish("heartbeatRequest",Z);c={timeout:3E4,onSuccess:function(Rv){if(!N.W.isActive()&&BF(N)){var Zu=
N.getVideoData(),Nx=Zu.Jx&&N.J==null,av;Zu.Jx=!((av=Rv.heartbeatAttestationConfig)==null||!av.requiresAttestation)||Nx;Nx=Rv.playabilityStatus;av=JSON.stringify(Nx)||"{}";Rv.authenticationMismatch&&N.player.WL("authshear",{});var M=-1;var s2=Rv.playabilityStatus;s2&&(N.player.Qp("onHeartbeat",s2),s2.status==="OK"?M=Rv.stopHeartbeat?2:0:s2.status==="UNPLAYABLE"?M=1:s2.status==="LIVE_STREAM_OFFLINE"&&(M=0));N.sequenceNumber&&M===-1||N.G.reset();N.sequenceNumber++;Rv.heartbeatServerData&&(N.Vp=Rv.heartbeatServerData);
Zu.sX=Rv;(s2=Rv.playerCueRangeSet)&&g.qN(Zu,s2);Rv.playerCueRanges&&Rv.playerCueRanges.length>0&&(Zu.cueRanges=Rv.playerCueRanges);var $m,O2;(($m=Rv.progressBarConfig)==null?0:$m.progressBarStartPosition)&&((O2=Rv.progressBarConfig)==null?0:O2.progressBarEndPosition)&&(Zu.progressBarStartPosition=Rv.progressBarConfig.progressBarStartPosition,Zu.progressBarEndPosition=Rv.progressBarConfig.progressBarEndPosition);Zu.compositeLiveIngestionOffsetToken=Rv.compositeLiveIngestionOffsetToken;Rv.compositeLiveStatusToken!==
Zu.compositeLiveStatusToken&&(Zu.compositeLiveStatusToken=Rv.compositeLiveStatusToken);Zu.publish("dataupdated");Hcm(N,Rv,Nx,av,M)}},
onError:function(Rv){BF(N)&&AP(N,!0,"net-"+Rv.status)},
onTimeout:function(){BF(N)&&AP(N,!0,"timeout")}};
g.CW(z,g.hf(v)).then(function(Rv){Rv&&(c.w9="Bearer "+Rv);g.w5(N.qd,R,Z,c)});
g.fO(r)})},Hcm=function(N,z,v,R,C){C===-1?(v="decode "+g.vJ(R,3),AP(N,!1,v)):C===2?(g7(N),N.B=!0):(N.Y=0,N.W.stop(),C===1?(N.B=!1,v&&v.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&N.player.Sl(!0),C="pe."+(v==null?void 0:v.errorCode)+";ps."+(v==null?void 0:v.status),N.player.Ij("heartbeat.stop",2,N.VX(R),C),g.aX("heartbeatActionPlayerHalted",IH8(v)),(z==null?0:z.videoTransitionEndpoint)&&v&&(z=z.videoTransitionEndpoint,(R=g.t(z,g.wi))&&XT5(N,R,v,{itct:z==null?void 0:z.clickTrackingParams}))):(N.B=
!0,R=0,N.N&&v&&(R=AF$(N,z,v),N.player.publish("livestatedata",v)),R?Ua(N,R):Ua(N)))},AF$=function(N,z,v){var R=v.liveStreamability&&v.liveStreamability.liveStreamabilityRenderer,C=!(!R||!(R.switchStreamsImmediately||R.transitionTiming&&R.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
z=rFm(N,z,R);var Z=N.getVideoData(),Y=N.player.getPlayerStateObject(N.getPlayerType()),Q=Y.isPlaying()&&!g.mw(Z)&&!N.player.isAtLiveHead(N.getPlayerType());if(Z.D().LV()){var L,K=((L=N.player.O6())==null?void 0:L.TE())||{};K.status=v.status||"";K.dvr=""+ +Q;K["switch"]=""+ +C;K.ended=""+ +!(!R||!R.displayEndscreen);N.player.WL("heartbeat",K)}L=N.player.X("always_cache_redirect_endpoint");if(Q&&!C&&!L)return z;K=R&&R.streamTransitionEndpoint&&g.t(R.streamTransitionEndpoint,g.wi);var l=R&&R.transitionTiming;
if(l==="STREAM_TRANSITION_TIMING_AT_STREAM_END")N.getVideoData().transitionEndpointAtEndOfStream=K;else if(L&&!K&&N.getVideoData().transitionEndpointAtEndOfStream)N.getVideoData().transitionEndpointAtEndOfStream=void 0;else if(!L&&K&&XT5(N,K,v))return z;if(Q&&!C&&L||L&&K&&(l==="STREAM_TRANSITION_TIMING_IMMEDIATELY"||l==="STREAM_TRANSITION_TIMING_UNSPECIFIED")&&XT5(N,K,v))return z;if(v.status.toUpperCase()==="OK"){C=R&&R.broadcastId;Q=N.V&&N.V.liveStreamability&&N.V.liveStreamability.liveStreamabilityRenderer&&
N.V.liveStreamability.liveStreamabilityRenderer.broadcastId;L=C!==Q&&C!=null;if(!g.Th(Z)||L){var W={video_id:Z.videoId};Z.FP&&(W.is_live_destination="1");W.disable_watch_next=!0;W.raw_watch_next_response=Z.getWatchNextResponse();W.autonav_state=Z.autonavState;W.oauth_token=Z.oauthToken;W.U5=Z.U5;Z.G&&(W.vss_credentials_token=Z.G,W.vss_credentials_token_type=Z.Jk);Z.Rd&&(W.vvt=Z.Rd);R=void 0;g.Th(Z)?L&&(R=new $v("broadcastIdChanged",Q+","+C),N.rT("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",
v)):(C&&(R=new $v("formatsReceived",""+C)),N.rT("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",v));N.player.loadVideoByPlayerVars(W,void 0,void 0,void 0,R);return z}N.player.kA("heartbeat",N.getPlayerType())}R&&R.displayEndscreen&&(N.offlineSlate?(N=N.offlineSlate,N.L=!0,N.Vh&&N.api.f_()):Y.isBuffering()&&(Z=((W=N.player.O6())==null?void 0:W.TE())||{},N.player.WL("hbse",Z,!0),N.player.f_(),N.player.Qp("onLiveMediaEnded",v)));return z},rFm=function(N,
z,v){return N.player.X("web_player_use_heartbeat_poll_delay_ms")&&(N=Number(z==null?void 0:z.pollDelayMs))?N:(v=Number(v==null?void 0:v.pollDelayMs))?v:0},AP=function(N,z,v){var R=N.player.D();
if(!N.W.isActive()){N.W.stop();N.Y++;var C=z?"heartbeat.net":"heartbeat.servererror";var Z=N.getVideoData();if(Z.I5||z&&!g.yO(N.getVideoData())&&!SJ$(N)&&Z.isLivePlayback)Z=!1;else{var Y,Q;((Q=N.heartbeatParams)==null?0:Q.retries)?Y=N.heartbeatParams.retries:Y=Z.Wy||5;Z=N.Y>=Y}Z?(g.aX("heartbeatActionPlayerHalted",z?{enforcedPolicyToHaltOnNetworkFailure:!0}:IH8()),(z=N.getVideoData())&&z.isLivePlayback?N.player.Ij(C,1,"Video playback interrupted. Please try again.",v):N.player.Ij(C,1,"Sorry, there was an error while licensing this video.",
v)):(R.X("html5_report_non_fatal_heartbeat_error")&&N.player.YM(C,{msg:v}),Ua(N,N.G.getValue()),g.Hf(N.G))}},IH8=function(N){var z={enforcedPolicyToHaltOnNetworkFailure:!1};
N&&(z.serializedServerContext=N.additionalLoggingData);return z},g7=function(N){N.Y=0;
N.W.stop();N.B=!1;N.sequenceNumber=0},BP7=function(N){var z=N.getVideoData(),v=N.player.D();
if(z.isLivePlayback)if(g.Cu(v.B)){N.N=!0;N.L=!0;if(!g.nM(v)||g.TW(v))N.offlineSlate=new nKP(N.player),g.b(N,N.offlineSlate),g.PX(N.player,N.offlineSlate.element,4);(z=z.getPlayerResponse())&&z.playabilityStatus&&(N.V=z.playabilityStatus);var R;((R=N.V)==null?void 0:R.status)!=="UNPLAYABLE"&&(N.V?(R=rFm(N,void 0,N.V.liveStreamability&&N.V.liveStreamability.liveStreamabilityRenderer))?Ua(N,R):Ua(N,7500):Ua(N,1E3))}else N.player.Ij("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.J8(z.PL,"heartbeat")&&N.player.kA("heartbeat",N.getPlayerType())},XT5=function(N,z,v,R){var C=z&&z.videoId;
return C?(N.player.n4(C,Object.assign({},{autonav:"1"},R||{}),void 0,!0,!0,z,g.hf(N.getVideoData())),N.rT("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",v),!0):!1},tNU=function(N){return(N=N.player.getProgressState(N.getPlayerType()).ingestionTime)&&isFinite(N)?""+Math.floor(N*1E3):null},Oc1=function(N){return(N=N.player.getCurrentTime(N.getPlayerType()))&&isFinite(N)?""+Math.floor(N*1E3):null},EKw=function(N){try{var z=JSON.parse(N);
return z!=null?z:void 0}catch(v){}},uO5={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
uO5={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["am","pm"],DATEFORMATS:["EEEE, d MMMM y",
"d MMMM y","d MMM y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:3};
var P_8=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],cF$={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.J=xWP.prototype;g.J.iN=uO5.FIRSTDAYOFWEEK;g.J.oi=uO5.FIRSTWEEKCUTOFFDAY;
g.J.clone=function(){var N=new xWP(this.date);N.iN=this.iN;N.oi=this.oi;return N};
g.J.getFullYear=function(){return this.date.getFullYear()};
g.J.getYear=function(){return this.getFullYear()};
g.J.getMonth=function(){return this.date.getMonth()};
g.J.getDate=function(){return this.date.getDate()};
g.J.getTime=function(){return this.date.getTime()};
g.J.getDay=function(){return this.date.getDay()};
g.J.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.J.getUTCMonth=function(){return this.date.getUTCMonth()};
g.J.getUTCDate=function(){return this.date.getUTCDate()};
g.J.getUTCDay=function(){return this.date.getDay()};
g.J.getUTCHours=function(){return this.date.getUTCHours()};
g.J.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.J.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.J.set=function(N){this.date=new Date(N.getFullYear(),N.getMonth(),N.getDate())};
g.J.setFullYear=function(N){this.date.setFullYear(N)};
g.J.setYear=function(N){this.setFullYear(N)};
g.J.setMonth=function(N){this.date.setMonth(N)};
g.J.setDate=function(N){this.date.setDate(N)};
g.J.setTime=function(N){this.date.setTime(N)};
g.J.setUTCFullYear=function(N){this.date.setUTCFullYear(N)};
g.J.setUTCMonth=function(N){this.date.setUTCMonth(N)};
g.J.setUTCDate=function(N){this.date.setUTCDate(N)};
g.J.add=function(N){if(N.years||N.months){var z=this.getMonth()+N.months+N.years*12,v=this.getYear()+Math.floor(z/12);z%=12;z<0&&(z+=12);a:{switch(z){case 1:var R=v%4!=0||v%100==0&&v%400!=0?28:29;break a;case 5:case 8:case 10:case 3:R=30;break a}R=31}R=Math.min(R,this.getDate());this.setDate(1);this.setFullYear(v);this.setMonth(z);this.setDate(R)}N.days&&(v=this.getYear(),z=v>=0&&v<=99?-1900:0,N=new Date((new Date(v,this.getMonth(),this.getDate(),12)).getTime()+N.days*864E5),this.setDate(1),this.setFullYear(N.getFullYear()+
z),this.setMonth(N.getMonth()),this.setDate(N.getDate()),Tw(this,N.getDate()))};
g.J.equals=function(N){return!(!N||this.getYear()!=N.getYear()||this.getMonth()!=N.getMonth()||this.getDate()!=N.getDate())};
g.J.toString=function(){var N=this.getFullYear(),z=N<0?"-":N>=1E4?"+":"";return[z+KAP(Math.abs(N),z?6:4),KAP(this.getMonth()+1,2),KAP(this.getDate(),2)].join("")+""};
g.J.valueOf=function(){return this.date.valueOf()};var qJ5=new g.ni("addUpcomingEventReminderEndpoint");var MNP=new g.ni("removeUpcomingEventReminderEndpoint");var wTW=new g.ni("updateUpcomingEventReminderButtonStateCommand");var JF$=new g.ni("upcomingEventReminderButtonRenderer"),FAZ=new g.ni("upcomingEventReminderButtonStateRenderer");g.y(Fw,g.D2);
Fw.prototype.updateMenuItems=function(){var N=this,z=eVV(this),v=0;v=0;for(var R={};v<z.length;R={Kq:void 0},v++){var C=this.Z[v];C||(C=new g.X({K:"div",U:"ytp-reminder-menu-item",T:{role:"menuitem",tabindex:"0"},j:[{K:"div",U:"ytp-reminder-menu-item-icon",OT:"{{icon}}"},{K:"div",U:"ytp-reminder-menu-item-label",OT:"{{text}}"}]}),R.Kq=v,C.listen("click",function(Y){return function(){var Q=Y.Kq;N.pV();Q=eVV(N)[Q];N.publish("reminderMenuItemClicked",Q.serviceEndpoint||Q.command)}}(R)),C.Nd(this.items),
this.Z[v]=C);
var Z=z[v];R=null;switch(Z.icon&&Z.icon.iconType){case "NOTIFICATIONS":R=lHr();break;case "NOTIFICATIONS_NONE":R=WA1();break;case "NOTIFICATIONS_ACTIVE":R=g.Fo()}Z=Z.text?g.xt(Z.text):"";C.update({icon:R,text:Z})}for(;v<this.Z.length;)this.Z.pop().dispose();v===0?this.pV():this.uF(this.V)};
Fw.prototype.hide=function(){this.V&&this.V.removeAttribute("aria-haspopup");g.D2.prototype.hide.call(this)};
Fw.prototype.show=function(){this.V&&this.V.setAttribute("aria-haspopup","true");g.D2.prototype.show.call(this)};
Fw.prototype.AO=function(){g.Kc(this.Z);g.D2.prototype.AO.call(this)};g.y(no,g.X);
no.prototype.L=function(){if(this.toggleButtonRenderer){var N=this.toggleButtonRenderer;N.isToggled?this.Z(N.toggledServiceEndpoint):this.Z(N.defaultServiceEndpoint);N.isToggled=!N.isToggled;m0(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.V&&this.V.Vh)this.V.pV();else{var z=dW9(this);z&&this.Z(z.serviceEndpoint||z.command);z=((N=g.t(z==null?void 0:z.command,g.xJ))==null?void 0:N.commands)||[];a:{N=g.f(z);for(var v=N.next();!v.done;v=N.next()){var R=z=void 0;if(v=(z=g.t(v.value,g.d88))==
null?void 0:(R=z.popup)==null?void 0:R.menuPopupRenderer){N=v;break a}}N=void 0}this.V||(this.V=new Fw(this.C,this.G),this.V.Nd(this.element),g.b(this,this.V),this.V.subscribe("reminderMenuItemClicked",this.Z,this));z=this.V;z.menuPopupRenderer=N;z.updateMenuItems()}};
no.prototype.Z=function(N){var z=g.t(N,qJ5),v=g.t(N,MNP);if(N&&(z||v)){if(z){var R=z;var C="notification/add_upcoming_event_reminder"}else v&&(R=v,C="notification/remove_upcoming_event_reminder");if(C&&R&&R.params)for(TPV(this,C,R.params),N=g.f(R.commands||[]),z=N.next();!z.done;z=N.next())if((z=z.value)&&g.t(z,wTW)){this.W=g.t(z,wTW).state;m0(this);break}}};g.y(nKP,g.X);g.J=nKP.prototype;g.J.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.J.getVideoData=function(){return g.h(this.api.getVideoData(this.getPlayerType()))};
g.J.FW=function(N){var z,v,R=N==null?void 0:(z=N.liveStreamability)==null?void 0:(v=z.liveStreamabilityRenderer)==null?void 0:v.offlineSlate;if(R){this.W=N;z=R.liveStreamOfflineSlateRenderer;z.canShowCountdown?this.wp():mWU(this,z);var C,Z,Y,Q;if(v=N==null?void 0:(C=N.liveStreamability)==null?void 0:(Z=C.liveStreamabilityRenderer)==null?void 0:(Y=Z.offlineSlate)==null?void 0:(Q=Y.liveStreamOfflineSlateRenderer)==null?void 0:Q.thumbnail){C=0;Z=null;Y=v.thumbnails;for(Q=0;Q<Y.length;Q++)Y[Q].width>
C&&(C=Y[Q].width||0,Z=Y[Q].url);Z&&(this.background.style.backgroundImage="url("+Z+")")}else this.background.style.backgroundImage="";z.actionButtons||z.reminderButton?(this.V||(this.V=new no(this.api),this.V.Nd(this.e8("ytp-offline-slate-buttons")),g.b(this,this.V)),yF$(this.V,z.actionButtons&&z.actionButtons[0],z.reminderButton)):this.V&&yF$(this.V,null,null);this.W=N}else this.W=null;this.Tv()};
g.J.Tv=function(N){if(this.api.getPresentingPlayerType()===8)var z=!0;else{var v=this.api.getPlayerStateObject(),R=this.getVideoData();z=R.isLivePlayback&&(v.isBuffering()||g.u(v,2)||g.u(v,64));var C=R.autonavState===2&&g.u(v,2);v=v.isPlaying()&&!g.mw(R)&&!this.api.isAtLiveHead(void 0,!0);z=z&&!v&&!C}z&&this.W?this.Vh?(N==null?0:g.WW(N,2))&&!this.getVideoData().V6&&(g.jW(this.element,"ytp-offline-slate-collapsed"),this.N.stop(),g.jW(this.Z,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),
this.N.start(),this.api.publish("offlineslatestatechange"),this.L&&this.api.f_()):this.Vh&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.J.wp=function(){var N,z,v,R,C=(N=this.W)==null?void 0:(z=N.liveStreamability)==null?void 0:(v=z.liveStreamabilityRenderer)==null?void 0:(R=v.offlineSlate)==null?void 0:R.liveStreamOfflineSlateRenderer;C&&(N=Math.floor(g.jV()/1E3),z=C.canShowCountdown&&Number(C.scheduledStartTime),!z||z<=N?(mWU(this,C),this.countdownTimer.stop()):(mWU(this,C,g.TX(z-N)),g.qv(this.countdownTimer)))};
g.J.AO=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.X.prototype.AO.call(this)};$v.prototype.W=function(N){return this.trigger&&N.trigger?this.trigger===N.trigger&&this.V===N.V:!1};
$v.prototype.isExpired=function(){return(0,g.I)()-this.Z>6E4};
$v.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.V};g.y(pTr,g.GI);g.J=pTr.prototype;g.J.AO=function(){g7(this);this.player.s6("heartbeat");g.GI.prototype.AO.call(this)};
g.J.onCueRangeEnter=function(){this.L=!0;Ua(this,2E3)};
g.J.sS=function(N){this.heartbeatParams=N;Ua(this,2E3)};
g.J.Z3=function(N){var z;this.player.getPresentingPlayerType()!==8&&((z=this.V)==null?void 0:z.status)!=="UNPLAYABLE"&&(g.u(N.state,2)||g.u(N.state,64)?(g7(this),this.N&&(this.L=!0,Ua(this,1E3))):(g.u(N.state,1)||g.u(N.state,8))&&Ua(this,2E3))};
g.J.Nn=function(){this.player.getPresentingPlayerType()!==3&&Ua(this,2E3)};
g.J.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.J.getVideoData=function(){return g.h(this.player.getVideoData(this.getPlayerType()))};
g.J.Do=function(N){switch(N){case 4:case 3:return!1}return!0};
g.J.rT=function(N,z,v){N={trigger:N,reason:z};v&&(N.serializedServerContext=v.additionalLoggingData);g.aX("heartbeatActionPlayerTransitioned",N)};
g.J.VX=function(N){var z="LICENSE",v=EKw(N);if(v)return v.reason||g.EG[z]||"";if(N=N.match(hVw))if(N=Number(N[1]))z=(z=cF$[N.toString()])?z:"LICENSE";return g.EG[z]||""};
g.J.cU=function(){return!!this.offlineSlate&&this.offlineSlate.Vh};
var hVw=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.Wb("heartbeat",pTr);})(_yt_player);
